import fc from 'fast-check';
import { neverThrows } from "../../../../../../tests/property-harness";
import { parseStruct, type StructFieldDef, type StructFieldType } from "@dude/tool-engine/tools/binary-structure-inspector/binary-structure-inspector-logic";

describe('parseStruct properties', () => {
  it('never throws for generated byte buffers and typed field sequences', () => {
    const types: StructFieldType[] = ['uint8', 'int8', 'uint16', 'int16', 'uint32', 'int32', 'uint64', 'int64', 'float32', 'float64', 'char'];
    const fields = fc.array(fc.record({ name: fc.string({ maxLength: 8 }), type: fc.constantFrom(...types), length: fc.integer({ min: 0, max: 16 }), endianness: fc.constantFrom('LE' as const, 'BE' as const) }), { maxLength: 12 }) as fc.Arbitrary<StructFieldDef[]>;
    neverThrows(([bytes, defs]: [Uint8Array, StructFieldDef[]]) => parseStruct(bytes, defs), fc.tuple(fc.uint8Array({ maxLength: 64 }), fields), {
      assertShape: (result) => expect((result as ReturnType<typeof parseStruct>).bytesConsumed).toBeLessThanOrEqual(64),
    });
  });
});
