import { describe, expect, it } from 'vitest';
import { parseYarnClassicLockfile } from "./lockfile-inspector-yarn-classic.js";

const SAMPLE = [
  '# THIS IS AN AUTOGENERATED FILE. DO NOT EDIT THIS FILE DIRECTLY.',
  '# yarn lockfile v1',
  '',
  '',
  'lodash@^4.17.21:',
  '  version "4.17.21"',
  '  resolved "https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abc123"',
  '  integrity sha512-abc123',
  '',
  '"@babel/core@^7.0.0", "@babel/core@^7.12.3":',
  '  version "7.20.0"',
  '  resolved "https://registry.yarnpkg.com/@babel/core/-/core-7.20.0.tgz#def456"',
  '  dependencies:',
  '    "@babel/code-frame" "^7.18.6"',
  '    semver "^6.3.0"',
  '',
].join('\n');

describe('parseYarnClassicLockfile', () => {
  it('parses a simple entry', () => {
    const result = parseYarnClassicLockfile(SAMPLE);
    const lodash = result.find((p) => p.name === 'lodash');
    expect(lodash?.version).toBe('4.17.21');
    expect(lodash?.resolved).toBe('https://registry.yarnpkg.com/lodash/-/lodash-4.17.21.tgz#abc123');
  });

  it('collapses multiple comma-separated range declarations to one entry named after the package', () => {
    const result = parseYarnClassicLockfile(SAMPLE);
    const babel = result.find((p) => p.name === '@babel/core');
    expect(babel?.version).toBe('7.20.0');
    expect(babel?.dependencies).toEqual(['@babel/code-frame', 'semver']);
  });

  it('returns exactly one entry per block', () => {
    expect(parseYarnClassicLockfile(SAMPLE)).toHaveLength(2);
  });
});
