import type { ToolMetadata } from "@dude/domain/shared/models/tool-metadata.model";
export const manifest: ToolMetadata = {
    id: 'byte-frequency-analyzer',
    title: 'Byte Frequency Analyzer',
    description: 'Charts how often each of the 256 byte values occurs in an uploaded file, and reports the most frequent byte and how many distinct values appear.',
    category: 'developer',
    keywords: ['byte frequency', 'histogram', 'byte distribution', 'forensics', 'binary analysis'],
    route: '/tools/byte-frequency-analyzer',
    status: 'verified',
    verification: {
        propertyTested: true,
        summary: 'Fuzzed byte histograms over generated byte arrays, checking all 256 bins and count totals.',
    },
    persistence: { input: 'none', preferences: 'none' },
    execution: { worker: 'optional' },
    io: { accepts: ['file'], produces: ['json'] }
};
