import type { ToolMetadata } from "@dude/domain/shared/models/tool-metadata.model";
export const manifest: ToolMetadata = {
    id: 'jwks-to-pem',
    title: 'JWKS → Public Keys',
    shortTitle: 'JWKS → PEM',
    description: 'Converts JWKS keys to PEM (SPKI) or raw JWK for use outside the browser.',
    category: 'security',
    keywords: ['jwks', 'jwk', 'pem', 'spki', 'public key', 'convert', 'export'],
    route: '/tools/jwks-to-pem',
    status: 'verified',
    verification: {
        vectors: ['RFC 7517 Appendix A.1 RSA public JWK modulus/exponent survive PEM conversion'],
        crossChecked: ["Node's crypto (generateKeyPairSync + createPublicKey)"],
        summary: 'A JWK generated by Node\'s crypto module (not jose) converts to a PEM that Node\'s own createPublicKey re-imports to an identical modulus/exponent.',
    },
    consequenceClass: ['crypto'],
    persistence: { input: 'none', preferences: 'local' },
    io: { accepts: ['text', 'json'], produces: ['text'] }
};
