// AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit.
import type { PipelineValue } from '@dude/contracts/shared/models/pipeline-step.model';
export const PARITY_FIXTURE_LOADERS: Readonly<Record<string, () => Promise<readonly { input: PipelineValue; expected?: PipelineValue }[]>>> = {
 'base64': () => import('@dude/tool-engine/tools/base64/base64.parity-fixtures').then(m => m.fixtures),
 'hash': () => import('@dude/tool-engine/tools/hash/hash.parity-fixtures').then(m => m.fixtures),
 'json': () => import('@dude/tool-engine/tools/json/json.parity-fixtures').then(m => m.fixtures),
};
