import assert from 'node:assert/strict';
import { test } from 'node:test';
import { createRequire } from 'node:module';
import { packageConfiguration, signingVariables } from '../scripts/mobile-package.mjs';

const { applySigning } = createRequire(import.meta.url)('../apps/mobile/plugins/with-preview-signing.cjs');

const env = Object.fromEntries(signingVariables.map(name => [name, 'fixture']));
test('preview package fails closed on missing signing configuration', () => {
  for (const name of signingVariables) {
    assert.throws(() => packageConfiguration({ ...env, [name]: '' }, '2.0.0', 'false', '800'), /signing is required/);
  }
});
test('preview versions follow full master history and Android limits', () => {
  assert.deepEqual(packageConfiguration(env, '2.0.0', 'false', '800'), { versionName: '2.0.800', versionCode: 800 });
  for (const [base, shallow, count] of [['2.0.0', 'true', '800'], ['2.0.8', 'false', '800'], ['2.0.0', 'false', '0'], ['2.0.0', 'false', '2100000001']]) {
    assert.throws(() => packageConfiguration(env, base, shallow, count));
  }
});

test('release signing checks resolved app tasks and preserves unrelated generated Gradle content', () => {
  const template = 'plugins { id "com.android.application" }\n';
  const generated = applySigning(template);
  assert.match(generated, /gradle\.taskGraph\.whenReady/);
  assert.match(generated, /graph\.allTasks\.any \{ it\.project == project && it\.name\.toLowerCase\(\)\.contains\('release'\)/);
  assert.doesNotMatch(generated, /startParameter\.taskNames/);
  for (const name of signingVariables) assert.ok(generated.includes(name));
  assert.match(generated, /buildTypes\.release\.signingConfig = signingConfigs\.dudePreview/);
  assert.doesNotMatch(generated, /storePassword ['"]/);
  const suffix = '\n// another plugin\n';
  assert.equal(applySigning(generated + suffix), generated + suffix);
});

test('repeated prebuild upgrades the original signing block and refuses an unrecognized block', () => {
  const legacy = `// DUDE preview signing (generated by with-preview-signing)
def dudeReleaseRequested = gradle.startParameter.taskNames.any { it.toLowerCase().contains('release') }
android {
    buildTypes.release.signingConfig = signingConfigs.dudePreview
}
`;
  const upgraded = applySigning(`// before\n${legacy}// after\n`);
  assert.match(upgraded, /gradle\.taskGraph\.whenReady/);
  assert.doesNotMatch(upgraded, /startParameter\.taskNames/);
  assert.ok(upgraded.startsWith('// before\n'));
  assert.ok(upgraded.endsWith('// after\n'));
  assert.equal((upgraded.match(/\/\/ DUDE preview signing/g) ?? []).length, 1);
  assert.throws(() => applySigning('// DUDE preview signing (generated by with-preview-signing)\nmalformed'), /Cannot safely replace/);
});
