import type { ToolDefinition } from '../../shared/models/tool-definition.model';

export const manifest: ToolDefinition = {
  id: 'byte-frequency-analyzer',
  title: 'Byte Frequency Analyzer',
  description:
    'Charts how often each of the 256 byte values occurs in an uploaded file, and reports the most frequent byte and how many distinct values appear.',
  category: 'developer',
  keywords: ['byte frequency', 'histogram', 'byte distribution', 'forensics', 'binary analysis'],
  route: '/tools/byte-frequency-analyzer',
  load: () => import('./byte-frequency-analyzer').then((m) => m.ByteFrequencyAnalyzer),
  status: 'verified',
  verification: {
    propertyTested: true,
    summary: 'Fuzzed byte histograms over generated byte arrays, checking all 256 bins and count totals.',
  },
  persistence: { input: 'none', preferences: 'none' },
  execution: { worker: 'optional' },
  io: { accepts: ['file'], produces: ['json'] },
};
