// AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit.
import type { ToolMetadata } from '@dude/domain/shared/models/tool-metadata.model';
import { manifest as tool0 } from './tools/accept-header-builder/accept-header-builder.manifest.js';
import { manifest as tool1 } from './tools/acl-inspector/acl-inspector.manifest.js';
import { manifest as tool2 } from './tools/advanced-diff/advanced-diff.manifest.js';
import { manifest as tool3 } from './tools/aes-encrypt-decrypt/aes-encrypt-decrypt.manifest.js';
import { manifest as tool4 } from './tools/archive-tool/archive-tool.manifest.js';
import { manifest as tool5 } from './tools/ascii-art-generator/ascii-art-generator.manifest.js';
import { manifest as tool6 } from './tools/ascii-table/ascii-table.manifest.js';
import { manifest as tool7 } from './tools/aspect-ratio-calculator/aspect-ratio-calculator.manifest.js';
import { manifest as tool8 } from './tools/asymmetric-key-generator/asymmetric-key-generator.manifest.js';
import { manifest as tool9 } from './tools/avro-viewer/avro-viewer.manifest.js';
import { manifest as tool10 } from './tools/aws-sigv4-inspector/aws-sigv4-inspector.manifest.js';
import { manifest as tool11 } from './tools/barcode-generator/barcode-generator.manifest.js';
import { manifest as tool12 } from './tools/barcode-reader/barcode-reader.manifest.js';
import { manifest as tool13 } from './tools/base-n-encoder/base-n-encoder.manifest.js';
import { manifest as tool14 } from './tools/base64/base64.manifest.js';
import { manifest as tool15 } from './tools/base64-image-viewer/base64-image-viewer.manifest.js';
import { manifest as tool16 } from './tools/basic-auth-generator/basic-auth-generator.manifest.js';
import { manifest as tool17 } from './tools/batch-operations/batch-operations.manifest.js';
import { manifest as tool18 } from './tools/batch-rename/batch-rename.manifest.js';
import { manifest as tool19 } from './tools/batch-text-converter/batch-text-converter.manifest.js';
import { manifest as tool20 } from './tools/bearer-token-builder/bearer-token-builder.manifest.js';
import { manifest as tool21 } from './tools/bigint-calculator/bigint-calculator.manifest.js';
import { manifest as tool22 } from './tools/binary-strings-extractor/binary-strings-extractor.manifest.js';
import { manifest as tool23 } from './tools/binary-structure-inspector/binary-structure-inspector.manifest.js';
import { manifest as tool24 } from './tools/bom-detector/bom-detector.manifest.js';
import { manifest as tool25 } from './tools/border-radius-generator/border-radius-generator.manifest.js';
import { manifest as tool26 } from './tools/box-shadow-generator/box-shadow-generator.manifest.js';
import { manifest as tool27 } from './tools/branch-name-generator/branch-name-generator.manifest.js';
import { manifest as tool28 } from './tools/bson-viewer/bson-viewer.manifest.js';
import { manifest as tool29 } from './tools/byte-frequency-analyzer/byte-frequency-analyzer.manifest.js';
import { manifest as tool30 } from './tools/cache-control-builder/cache-control-builder.manifest.js';
import { manifest as tool31 } from './tools/case-converter/case-converter.manifest.js';
import { manifest as tool32 } from './tools/cbor-viewer/cbor-viewer.manifest.js';
import { manifest as tool33 } from './tools/certificate-chain-tools/certificate-chain-tools.manifest.js';
import { manifest as tool34 } from './tools/certificate-watch-list/certificate-watch-list.manifest.js';
import { manifest as tool35 } from './tools/chacha20-poly1305/chacha20-poly1305.manifest.js';
import { manifest as tool36 } from './tools/chmod-converter/chmod-converter.manifest.js';
import { manifest as tool37 } from './tools/cidr-calculator/cidr-calculator.manifest.js';
import { manifest as tool38 } from './tools/color-blindness-simulator/color-blindness-simulator.manifest.js';
import { manifest as tool39 } from './tools/color-converter/color-converter.manifest.js';
import { manifest as tool40 } from './tools/commit-message-validator/commit-message-validator.manifest.js';
import { manifest as tool41 } from './tools/compression-lab/compression-lab.manifest.js';
import { manifest as tool42 } from './tools/config-file-comparator/config-file-comparator.manifest.js';
import { manifest as tool43 } from './tools/config-merge-tool/config-merge-tool.manifest.js';
import { manifest as tool44 } from './tools/connectivity-tester/connectivity-tester.manifest.js';
import { manifest as tool45 } from './tools/content-disposition-builder/content-disposition-builder.manifest.js';
import { manifest as tool46 } from './tools/contrast-checker/contrast-checker.manifest.js';
import { manifest as tool47 } from './tools/conventional-commit-builder/conventional-commit-builder.manifest.js';
import { manifest as tool48 } from './tools/cookie-tools/cookie-tools.manifest.js';
import { manifest as tool49 } from './tools/cors-header-builder/cors-header-builder.manifest.js';
import { manifest as tool50 } from './tools/create-table-generator/create-table-generator.manifest.js';
import { manifest as tool51 } from './tools/cron/cron.manifest.js';
import { manifest as tool52 } from './tools/csp-builder/csp-builder.manifest.js';
import { manifest as tool53 } from './tools/csr-generator-inspector/csr-generator-inspector.manifest.js';
import { manifest as tool54 } from './tools/css-animation-builder/css-animation-builder.manifest.js';
import { manifest as tool55 } from './tools/css-formatter/css-formatter.manifest.js';
import { manifest as tool56 } from './tools/css-grid-playground/css-grid-playground.manifest.js';
import { manifest as tool57 } from './tools/css-selector-tester/css-selector-tester.manifest.js';
import { manifest as tool58 } from './tools/css-specificity-calculator/css-specificity-calculator.manifest.js';
import { manifest as tool59 } from './tools/css-transform-builder/css-transform-builder.manifest.js';
import { manifest as tool60 } from './tools/csv-cleaner/csv-cleaner.manifest.js';
import { manifest as tool61 } from './tools/csv-dedupe/csv-dedupe.manifest.js';
import { manifest as tool62 } from './tools/csv-delimiter-detector/csv-delimiter-detector.manifest.js';
import { manifest as tool63 } from './tools/csv-filter-sort/csv-filter-sort.manifest.js';
import { manifest as tool64 } from './tools/csv-join/csv-join.manifest.js';
import { manifest as tool65 } from './tools/csv-pivot/csv-pivot.manifest.js';
import { manifest as tool66 } from './tools/csv-sql/csv-sql.manifest.js';
import { manifest as tool67 } from './tools/csv-stats/csv-stats.manifest.js';
import { manifest as tool68 } from './tools/csv-viewer/csv-viewer.manifest.js';
import { manifest as tool69 } from './tools/ct-lookup/ct-lookup.manifest.js';
import { manifest as tool70 } from './tools/cubic-bezier-editor/cubic-bezier-editor.manifest.js';
import { manifest as tool71 } from './tools/cuid-generator/cuid-generator.manifest.js';
import { manifest as tool72 } from './tools/curl-converter/curl-converter.manifest.js';
import { manifest as tool73 } from './tools/data-uri-converter/data-uri-converter.manifest.js';
import { manifest as tool74 } from './tools/date-calculator/date-calculator.manifest.js';
import { manifest as tool75 } from './tools/dependency-version-comparator/dependency-version-comparator.manifest.js';
import { manifest as tool76 } from './tools/dependency-walker/dependency-walker.manifest.js';
import { manifest as tool77 } from './tools/dev-snippets-reference/dev-snippets-reference.manifest.js';
import { manifest as tool78 } from './tools/diff/diff.manifest.js';
import { manifest as tool79 } from './tools/directory-diff/directory-diff.manifest.js';
import { manifest as tool80 } from './tools/directory-tree-generator/directory-tree-generator.manifest.js';
import { manifest as tool81 } from './tools/dns-lookup/dns-lookup.manifest.js';
import { manifest as tool82 } from './tools/dns-propagation/dns-propagation.manifest.js';
import { manifest as tool83 } from './tools/dnssec-inspector/dnssec-inspector.manifest.js';
import { manifest as tool84 } from './tools/docker-compose-validator/docker-compose-validator.manifest.js';
import { manifest as tool85 } from './tools/docker-run-compose-converter/docker-run-compose-converter.manifest.js';
import { manifest as tool86 } from './tools/dockerfile-linter/dockerfile-linter.manifest.js';
import { manifest as tool87 } from './tools/dom-tree-viewer/dom-tree-viewer.manifest.js';
import { manifest as tool88 } from './tools/dpi-calculator/dpi-calculator.manifest.js';
import { manifest as tool89 } from './tools/dst-transition-explorer/dst-transition-explorer.manifest.js';
import { manifest as tool90 } from './tools/duplicate-files/duplicate-files.manifest.js';
import { manifest as tool91 } from './tools/duplicate-finder/duplicate-finder.manifest.js';
import { manifest as tool92 } from './tools/duration-formatter/duration-formatter.manifest.js';
import { manifest as tool93 } from './tools/elf-header-viewer/elf-header-viewer.manifest.js';
import { manifest as tool94 } from './tools/email-auth-inspector/email-auth-inspector.manifest.js';
import { manifest as tool95 } from './tools/encoding-detector/encoding-detector.manifest.js';
import { manifest as tool96 } from './tools/env-diff/env-diff.manifest.js';
import { manifest as tool97 } from './tools/env-editor/env-editor.manifest.js';
import { manifest as tool98 } from './tools/env-json-converter/env-json-converter.manifest.js';
import { manifest as tool99 } from './tools/env-validator/env-validator.manifest.js';
import { manifest as tool100 } from './tools/environment-variables/environment-variables.manifest.js';
import { manifest as tool101 } from './tools/epoch-timeline-visualizer/epoch-timeline-visualizer.manifest.js';
import { manifest as tool102 } from './tools/error-code-reference/error-code-reference.manifest.js';
import { manifest as tool103 } from './tools/escape-unescape-toolkit/escape-unescape-toolkit.manifest.js';
import { manifest as tool104 } from './tools/event-log-viewer/event-log-viewer.manifest.js';
import { manifest as tool105 } from './tools/exif-viewer/exif-viewer.manifest.js';
import { manifest as tool106 } from './tools/expression-evaluator/expression-evaluator.manifest.js';
import { manifest as tool107 } from './tools/extract-columns/extract-columns.manifest.js';
import { manifest as tool108 } from './tools/file-base64/file-base64.manifest.js';
import { manifest as tool109 } from './tools/file-entropy-analyzer/file-entropy-analyzer.manifest.js';
import { manifest as tool110 } from './tools/file-hash/file-hash.manifest.js';
import { manifest as tool111 } from './tools/file-inspector/file-inspector.manifest.js';
import { manifest as tool112 } from './tools/file-lock-inspector/file-lock-inspector.manifest.js';
import { manifest as tool113 } from './tools/file-split-join/file-split-join.manifest.js';
import { manifest as tool114 } from './tools/file-type-detector/file-type-detector.manifest.js';
import { manifest as tool115 } from './tools/find-replace-text/find-replace-text.manifest.js';
import { manifest as tool116 } from './tools/flexbox-playground/flexbox-playground.manifest.js';
import { manifest as tool117 } from './tools/folder-size-analyzer/folder-size-analyzer.manifest.js';
import { manifest as tool118 } from './tools/git-command-builder/git-command-builder.manifest.js';
import { manifest as tool119 } from './tools/git-command-explainer/git-command-explainer.manifest.js';
import { manifest as tool120 } from './tools/git-diff/git-diff.manifest.js';
import { manifest as tool121 } from './tools/git-remote-inspector/git-remote-inspector.manifest.js';
import { manifest as tool122 } from './tools/git-url-parser/git-url-parser.manifest.js';
import { manifest as tool123 } from './tools/gitignore-generator/gitignore-generator.manifest.js';
import { manifest as tool124 } from './tools/gitignore-tester/gitignore-tester.manifest.js';
import { manifest as tool125 } from './tools/glob-tester/glob-tester.manifest.js';
import { manifest as tool126 } from './tools/gradient-generator/gradient-generator.manifest.js';
import { manifest as tool127 } from './tools/hash/hash.manifest.js';
import { manifest as tool128 } from './tools/hash-manifest/hash-manifest.manifest.js';
import { manifest as tool129 } from './tools/hex-diff/hex-diff.manifest.js';
import { manifest as tool130 } from './tools/hex-dump/hex-dump.manifest.js';
import { manifest as tool131 } from './tools/hex-editor/hex-editor.manifest.js';
import { manifest as tool132 } from './tools/hex-text-converter/hex-text-converter.manifest.js';
import { manifest as tool133 } from './tools/hmac-generator/hmac-generator.manifest.js';
import { manifest as tool134 } from './tools/hostname-resolver/hostname-resolver.manifest.js';
import { manifest as tool135 } from './tools/html-entities/html-entities.manifest.js';
import { manifest as tool136 } from './tools/html-entity-explorer/html-entity-explorer.manifest.js';
import { manifest as tool137 } from './tools/html-formatter/html-formatter.manifest.js';
import { manifest as tool138 } from './tools/html-jsx-converter/html-jsx-converter.manifest.js';
import { manifest as tool139 } from './tools/html-preview/html-preview.manifest.js';
import { manifest as tool140 } from './tools/http-digest-auth-helper/http-digest-auth-helper.manifest.js';
import { manifest as tool141 } from './tools/http-header-inspector/http-header-inspector.manifest.js';
import { manifest as tool142 } from './tools/http-request-builder/http-request-builder.manifest.js';
import { manifest as tool143 } from './tools/http-response-viewer/http-response-viewer.manifest.js';
import { manifest as tool144 } from './tools/http-status/http-status.manifest.js';
import { manifest as tool145 } from './tools/https-config-analyzer/https-config-analyzer.manifest.js';
import { manifest as tool146 } from './tools/image-compressor/image-compressor.manifest.js';
import { manifest as tool147 } from './tools/image-cropper/image-cropper.manifest.js';
import { manifest as tool148 } from './tools/image-format-converter/image-format-converter.manifest.js';
import { manifest as tool149 } from './tools/image-metadata-inspector/image-metadata-inspector.manifest.js';
import { manifest as tool150 } from './tools/image-resizer/image-resizer.manifest.js';
import { manifest as tool151 } from './tools/ini-formatter/ini-formatter.manifest.js';
import { manifest as tool152 } from './tools/installed-software/installed-software.manifest.js';
import { manifest as tool153 } from './tools/invisible-char-scanner/invisible-char-scanner.manifest.js';
import { manifest as tool154 } from './tools/ip-address-inspector/ip-address-inspector.manifest.js';
import { manifest as tool155 } from './tools/ipv4-integer-converter/ipv4-integer-converter.manifest.js';
import { manifest as tool156 } from './tools/ipv6-explorer/ipv6-explorer.manifest.js';
import { manifest as tool157 } from './tools/js-playground/js-playground.manifest.js';
import { manifest as tool158 } from './tools/json/json.manifest.js';
import { manifest as tool159 } from './tools/json-flatten/json-flatten.manifest.js';
import { manifest as tool160 } from './tools/json-ld-tester/json-ld-tester.manifest.js';
import { manifest as tool161 } from './tools/json-merge/json-merge.manifest.js';
import { manifest as tool162 } from './tools/json-patch-generate/json-patch-generate.manifest.js';
import { manifest as tool163 } from './tools/json-patch-test/json-patch-test.manifest.js';
import { manifest as tool164 } from './tools/json-pointer/json-pointer.manifest.js';
import { manifest as tool165 } from './tools/json-query/json-query.manifest.js';
import { manifest as tool166 } from './tools/json-schema-validator/json-schema-validator.manifest.js';
import { manifest as tool167 } from './tools/json-sort-keys/json-sort-keys.manifest.js';
import { manifest as tool168 } from './tools/jsonl-viewer/jsonl-viewer.manifest.js';
import { manifest as tool169 } from './tools/jwks-to-pem/jwks-to-pem.manifest.js';
import { manifest as tool170 } from './tools/jwks-viewer/jwks-viewer.manifest.js';
import { manifest as tool171 } from './tools/jwt/jwt.manifest.js';
import { manifest as tool172 } from './tools/jwt-claims-analyzer/jwt-claims-analyzer.manifest.js';
import { manifest as tool173 } from './tools/jwt-expiration-visualizer/jwt-expiration-visualizer.manifest.js';
import { manifest as tool174 } from './tools/jwt-signer/jwt-signer.manifest.js';
import { manifest as tool175 } from './tools/jwt-verify/jwt-verify.manifest.js';
import { manifest as tool176 } from './tools/k8s-cronjob-tester/k8s-cronjob-tester.manifest.js';
import { manifest as tool177 } from './tools/k8s-manifest-diff/k8s-manifest-diff.manifest.js';
import { manifest as tool178 } from './tools/k8s-manifest-validator/k8s-manifest-validator.manifest.js';
import { manifest as tool179 } from './tools/k8s-quantity-converter/k8s-quantity-converter.manifest.js';
import { manifest as tool180 } from './tools/k8s-resource-calculator/k8s-resource-calculator.manifest.js';
import { manifest as tool181 } from './tools/k8s-secret-base64/k8s-secret-base64.manifest.js';
import { manifest as tool182 } from './tools/keyword-frequency-analyzer/keyword-frequency-analyzer.manifest.js';
import { manifest as tool183 } from './tools/ksuid-tools/ksuid-tools.manifest.js';
import { manifest as tool184 } from './tools/kubeconfig-inspector/kubeconfig-inspector.manifest.js';
import { manifest as tool185 } from './tools/large-file-inspector/large-file-inspector.manifest.js';
import { manifest as tool186 } from './tools/latency-monitor/latency-monitor.manifest.js';
import { manifest as tool187 } from './tools/line-order-tools/line-order-tools.manifest.js';
import { manifest as tool188 } from './tools/line-prefix-numbering/line-prefix-numbering.manifest.js';
import { manifest as tool189 } from './tools/live-certificate-chain/live-certificate-chain.manifest.js';
import { manifest as tool190 } from './tools/local-network/local-network.manifest.js';
import { manifest as tool191 } from './tools/lockfile-inspector/lockfile-inspector.manifest.js';
import { manifest as tool192 } from './tools/lorem-ipsum-generator/lorem-ipsum-generator.manifest.js';
import { manifest as tool193 } from './tools/mac-address-inspector/mac-address-inspector.manifest.js';
import { manifest as tool194 } from './tools/macho-header-viewer/macho-header-viewer.manifest.js';
import { manifest as tool195 } from './tools/markdown/markdown.manifest.js';
import { manifest as tool196 } from './tools/markdown-workspace/markdown-workspace.manifest.js';
import { manifest as tool197 } from './tools/matrix-calculator/matrix-calculator.manifest.js';
import { manifest as tool198 } from './tools/meta-tag-generator/meta-tag-generator.manifest.js';
import { manifest as tool199 } from './tools/mime-types/mime-types.manifest.js';
import { manifest as tool200 } from './tools/missing-env-var-detector/missing-env-var-detector.manifest.js';
import { manifest as tool201 } from './tools/mock-data-studio/mock-data-studio.manifest.js';
import { manifest as tool202 } from './tools/model-generator/model-generator.manifest.js';
import { manifest as tool203 } from './tools/msgpack-decoder/msgpack-decoder.manifest.js';
import { manifest as tool204 } from './tools/mtu-discovery/mtu-discovery.manifest.js';
import { manifest as tool205 } from './tools/multipart-form-builder/multipart-form-builder.manifest.js';
import { manifest as tool206 } from './tools/nanoid-generator/nanoid-generator.manifest.js';
import { manifest as tool207 } from './tools/network-diagnostic-bundle/network-diagnostic-bundle.manifest.js';
import { manifest as tool208 } from './tools/number-base/number-base.manifest.js';
import { manifest as tool209 } from './tools/number-theory-toolkit/number-theory-toolkit.manifest.js';
import { manifest as tool210 } from './tools/numeric-representation-inspector/numeric-representation-inspector.manifest.js';
import { manifest as tool211 } from './tools/oauth-playground/oauth-playground.manifest.js';
import { manifest as tool212 } from './tools/oauth-scope-parser/oauth-scope-parser.manifest.js';
import { manifest as tool213 } from './tools/oauth-token-inspector/oauth-token-inspector.manifest.js';
import { manifest as tool214 } from './tools/oidc-discovery-inspector/oidc-discovery-inspector.manifest.js';
import { manifest as tool215 } from './tools/opengraph-preview/opengraph-preview.manifest.js';
import { manifest as tool216 } from './tools/package-metadata-inspector/package-metadata-inspector.manifest.js';
import { manifest as tool217 } from './tools/packet-loss/packet-loss.manifest.js';
import { manifest as tool218 } from './tools/palette-generator/palette-generator.manifest.js';
import { manifest as tool219 } from './tools/parquet-viewer/parquet-viewer.manifest.js';
import { manifest as tool220 } from './tools/password-generator/password-generator.manifest.js';
import { manifest as tool221 } from './tools/password-strength-analyzer/password-strength-analyzer.manifest.js';
import { manifest as tool222 } from './tools/path-editor/path-editor.manifest.js';
import { manifest as tool223 } from './tools/pe-header-viewer/pe-header-viewer.manifest.js';
import { manifest as tool224 } from './tools/pem-der-inspector/pem-der-inspector.manifest.js';
import { manifest as tool225 } from './tools/percentage-ratio-calculator/percentage-ratio-calculator.manifest.js';
import { manifest as tool226 } from './tools/ping/ping.manifest.js';
import { manifest as tool227 } from './tools/pixel-color-picker/pixel-color-picker.manifest.js';
import { manifest as tool228 } from './tools/pkce-generator/pkce-generator.manifest.js';
import { manifest as tool229 } from './tools/pkce-verifier/pkce-verifier.manifest.js';
import { manifest as tool230 } from './tools/pkcs12-inspector/pkcs12-inspector.manifest.js';
import { manifest as tool231 } from './tools/port-process-lookup/port-process-lookup.manifest.js';
import { manifest as tool232 } from './tools/port-scanner/port-scanner.manifest.js';
import { manifest as tool233 } from './tools/powershell-builder/powershell-builder.manifest.js';
import { manifest as tool234 } from './tools/process-diagnostic-bundle/process-diagnostic-bundle.manifest.js';
import { manifest as tool235 } from './tools/process-viewer/process-viewer.manifest.js';
import { manifest as tool236 } from './tools/programmer-calculator/programmer-calculator.manifest.js';
import { manifest as tool237 } from './tools/properties-parser/properties-parser.manifest.js';
import { manifest as tool238 } from './tools/protobuf-decoder/protobuf-decoder.manifest.js';
import { manifest as tool239 } from './tools/public-ip/public-ip.manifest.js';
import { manifest as tool240 } from './tools/punycode-converter/punycode-converter.manifest.js';
import { manifest as tool241 } from './tools/python-playground/python-playground.manifest.js';
import { manifest as tool242 } from './tools/qr-code-generator/qr-code-generator.manifest.js';
import { manifest as tool243 } from './tools/qr-code-scanner/qr-code-scanner.manifest.js';
import { manifest as tool244 } from './tools/query-string/query-string.manifest.js';
import { manifest as tool245 } from './tools/random-data-generator/random-data-generator.manifest.js';
import { manifest as tool246 } from './tools/range-generator/range-generator.manifest.js';
import { manifest as tool247 } from './tools/range-header-builder/range-header-builder.manifest.js';
import { manifest as tool248 } from './tools/recurrence-rule/recurrence-rule.manifest.js';
import { manifest as tool249 } from './tools/regex/regex.manifest.js';
import { manifest as tool250 } from './tools/regex-benchmark/regex-benchmark.manifest.js';
import { manifest as tool251 } from './tools/regex-flavor-converter/regex-flavor-converter.manifest.js';
import { manifest as tool252 } from './tools/regex-generator/regex-generator.manifest.js';
import { manifest as tool253 } from './tools/regex-visualizer/regex-visualizer.manifest.js';
import { manifest as tool254 } from './tools/registry-editor/registry-editor.manifest.js';
import { manifest as tool255 } from './tools/relative-time-parser/relative-time-parser.manifest.js';
import { manifest as tool256 } from './tools/resolution-calculator/resolution-calculator.manifest.js';
import { manifest as tool257 } from './tools/resx-tool/resx-tool.manifest.js';
import { manifest as tool258 } from './tools/reverse-dns/reverse-dns.manifest.js';
import { manifest as tool259 } from './tools/revocation-inspector/revocation-inspector.manifest.js';
import { manifest as tool260 } from './tools/rich-text-editor/rich-text-editor.manifest.js';
import { manifest as tool261 } from './tools/rot-cipher/rot-cipher.manifest.js';
import { manifest as tool262 } from './tools/route-comparison/route-comparison.manifest.js';
import { manifest as tool263 } from './tools/runtime-detector/runtime-detector.manifest.js';
import { manifest as tool264 } from './tools/scheduled-tasks/scheduled-tasks.manifest.js';
import { manifest as tool265 } from './tools/schema-diff/schema-diff.manifest.js';
import { manifest as tool266 } from './tools/scientific-notation-converter/scientific-notation-converter.manifest.js';
import { manifest as tool267 } from './tools/secret-detector/secret-detector.manifest.js';
import { manifest as tool268 } from './tools/semver-comparator/semver-comparator.manifest.js';
import { manifest as tool269 } from './tools/services-viewer/services-viewer.manifest.js';
import { manifest as tool270 } from './tools/sid-account-resolver/sid-account-resolver.manifest.js';
import { manifest as tool271 } from './tools/slug-generator/slug-generator.manifest.js';
import { manifest as tool272 } from './tools/smart-quotes-normalizer/smart-quotes-normalizer.manifest.js';
import { manifest as tool273 } from './tools/snowflake-id-tools/snowflake-id-tools.manifest.js';
import { manifest as tool274 } from './tools/soundex-metaphone/soundex-metaphone.manifest.js';
import { manifest as tool275 } from './tools/sql-dialect-converter/sql-dialect-converter.manifest.js';
import { manifest as tool276 } from './tools/sql-formatter-tool/sql-formatter-tool.manifest.js';
import { manifest as tool277 } from './tools/sql-parameterizer/sql-parameterizer.manifest.js';
import { manifest as tool278 } from './tools/sql-query-explainer/sql-query-explainer.manifest.js';
import { manifest as tool279 } from './tools/sql-syntax-checker/sql-syntax-checker.manifest.js';
import { manifest as tool280 } from './tools/sqlite-viewer/sqlite-viewer.manifest.js';
import { manifest as tool281 } from './tools/ssh-key-tools/ssh-key-tools.manifest.js';
import { manifest as tool282 } from './tools/stack-trace-formatter/stack-trace-formatter.manifest.js';
import { manifest as tool283 } from './tools/starttls-inspector/starttls-inspector.manifest.js';
import { manifest as tool284 } from './tools/startup-programs/startup-programs.manifest.js';
import { manifest as tool285 } from './tools/statistics-calculator/statistics-calculator.manifest.js';
import { manifest as tool286 } from './tools/stopwatch-countdown/stopwatch-countdown.manifest.js';
import { manifest as tool287 } from './tools/string-similarity-calculator/string-similarity-calculator.manifest.js';
import { manifest as tool288 } from './tools/structured-data-converter/structured-data-converter.manifest.js';
import { manifest as tool289 } from './tools/subnet-calculator/subnet-calculator.manifest.js';
import { manifest as tool290 } from './tools/svg-data-uri/svg-data-uri.manifest.js';
import { manifest as tool291 } from './tools/svg-viewer/svg-viewer.manifest.js';
import { manifest as tool292 } from './tools/system-changes/system-changes.manifest.js';
import { manifest as tool293 } from './tools/tailwind-color-matcher/tailwind-color-matcher.manifest.js';
import { manifest as tool294 } from './tools/tcp-port-tester/tcp-port-tester.manifest.js';
import { manifest as tool295 } from './tools/template-renderer/template-renderer.manifest.js';
import { manifest as tool296 } from './tools/text-inspector/text-inspector.manifest.js';
import { manifest as tool297 } from './tools/text-tokenizer-ngram/text-tokenizer-ngram.manifest.js';
import { manifest as tool298 } from './tools/timezone-converter/timezone-converter.manifest.js';
import { manifest as tool299 } from './tools/timezone-offset-comparator/timezone-offset-comparator.manifest.js';
import { manifest as tool300 } from './tools/tls-inspector/tls-inspector.manifest.js';
import { manifest as tool301 } from './tools/toml-formatter/toml-formatter.manifest.js';
import { manifest as tool302 } from './tools/traceroute/traceroute.manifest.js';
import { manifest as tool303 } from './tools/tree-search/tree-search.manifest.js';
import { manifest as tool304 } from './tools/udp-port-tester/udp-port-tester.manifest.js';
import { manifest as tool305 } from './tools/ulid-tools/ulid-tools.manifest.js';
import { manifest as tool306 } from './tools/unicode-character-inspector/unicode-character-inspector.manifest.js';
import { manifest as tool307 } from './tools/unicode-code-point-converter/unicode-code-point-converter.manifest.js';
import { manifest as tool308 } from './tools/unicode-normalization/unicode-normalization.manifest.js';
import { manifest as tool309 } from './tools/unicode-table/unicode-table.manifest.js';
import { manifest as tool310 } from './tools/unix-timestamp/unix-timestamp.manifest.js';
import { manifest as tool311 } from './tools/url-encode/url-encode.manifest.js';
import { manifest as tool312 } from './tools/url-inspector/url-inspector.manifest.js';
import { manifest as tool313 } from './tools/url-normalizer/url-normalizer.manifest.js';
import { manifest as tool314 } from './tools/url-percent-inspector/url-percent-inspector.manifest.js';
import { manifest as tool315 } from './tools/url-safety-inspector/url-safety-inspector.manifest.js';
import { manifest as tool316 } from './tools/user-agent/user-agent.manifest.js';
import { manifest as tool317 } from './tools/uuid/uuid.manifest.js';
import { manifest as tool318 } from './tools/watched-folders/watched-folders.manifest.js';
import { manifest as tool319 } from './tools/week-number-calculator/week-number-calculator.manifest.js';
import { manifest as tool320 } from './tools/whitespace-cleaner/whitespace-cleaner.manifest.js';
import { manifest as tool321 } from './tools/whois-lookup/whois-lookup.manifest.js';
import { manifest as tool322 } from './tools/windows-features/windows-features.manifest.js';
import { manifest as tool323 } from './tools/x509-certificate-inspector/x509-certificate-inspector.manifest.js';
import { manifest as tool324 } from './tools/xml-csv/xml-csv.manifest.js';
import { manifest as tool325 } from './tools/xml-formatter/xml-formatter.manifest.js';
import { manifest as tool326 } from './tools/xml-xpath/xml-xpath.manifest.js';
import { manifest as tool327 } from './tools/xml-xsd-validator/xml-xsd-validator.manifest.js';
import { manifest as tool328 } from './tools/yaml-anchors/yaml-anchors.manifest.js';
import { manifest as tool329 } from './tools/yaml-json/yaml-json.manifest.js';
import { manifest as tool330 } from './tools/yaml-linter/yaml-linter.manifest.js';
import { manifest as tool331 } from './tools/yaml-merge/yaml-merge.manifest.js';
import { manifest as tool332 } from './tools/yaml-path/yaml-path.manifest.js';
export const TOOL_METADATA: readonly ToolMetadata[] = [
 tool0,
 tool1,
 tool2,
 tool3,
 tool4,
 tool5,
 tool6,
 tool7,
 tool8,
 tool9,
 tool10,
 tool11,
 tool12,
 tool13,
 tool14,
 tool15,
 tool16,
 tool17,
 tool18,
 tool19,
 tool20,
 tool21,
 tool22,
 tool23,
 tool24,
 tool25,
 tool26,
 tool27,
 tool28,
 tool29,
 tool30,
 tool31,
 tool32,
 tool33,
 tool34,
 tool35,
 tool36,
 tool37,
 tool38,
 tool39,
 tool40,
 tool41,
 tool42,
 tool43,
 tool44,
 tool45,
 tool46,
 tool47,
 tool48,
 tool49,
 tool50,
 tool51,
 tool52,
 tool53,
 tool54,
 tool55,
 tool56,
 tool57,
 tool58,
 tool59,
 tool60,
 tool61,
 tool62,
 tool63,
 tool64,
 tool65,
 tool66,
 tool67,
 tool68,
 tool69,
 tool70,
 tool71,
 tool72,
 tool73,
 tool74,
 tool75,
 tool76,
 tool77,
 tool78,
 tool79,
 tool80,
 tool81,
 tool82,
 tool83,
 tool84,
 tool85,
 tool86,
 tool87,
 tool88,
 tool89,
 tool90,
 tool91,
 tool92,
 tool93,
 tool94,
 tool95,
 tool96,
 tool97,
 tool98,
 tool99,
 tool100,
 tool101,
 tool102,
 tool103,
 tool104,
 tool105,
 tool106,
 tool107,
 tool108,
 tool109,
 tool110,
 tool111,
 tool112,
 tool113,
 tool114,
 tool115,
 tool116,
 tool117,
 tool118,
 tool119,
 tool120,
 tool121,
 tool122,
 tool123,
 tool124,
 tool125,
 tool126,
 tool127,
 tool128,
 tool129,
 tool130,
 tool131,
 tool132,
 tool133,
 tool134,
 tool135,
 tool136,
 tool137,
 tool138,
 tool139,
 tool140,
 tool141,
 tool142,
 tool143,
 tool144,
 tool145,
 tool146,
 tool147,
 tool148,
 tool149,
 tool150,
 tool151,
 tool152,
 tool153,
 tool154,
 tool155,
 tool156,
 tool157,
 tool158,
 tool159,
 tool160,
 tool161,
 tool162,
 tool163,
 tool164,
 tool165,
 tool166,
 tool167,
 tool168,
 tool169,
 tool170,
 tool171,
 tool172,
 tool173,
 tool174,
 tool175,
 tool176,
 tool177,
 tool178,
 tool179,
 tool180,
 tool181,
 tool182,
 tool183,
 tool184,
 tool185,
 tool186,
 tool187,
 tool188,
 tool189,
 tool190,
 tool191,
 tool192,
 tool193,
 tool194,
 tool195,
 tool196,
 tool197,
 tool198,
 tool199,
 tool200,
 tool201,
 tool202,
 tool203,
 tool204,
 tool205,
 tool206,
 tool207,
 tool208,
 tool209,
 tool210,
 tool211,
 tool212,
 tool213,
 tool214,
 tool215,
 tool216,
 tool217,
 tool218,
 tool219,
 tool220,
 tool221,
 tool222,
 tool223,
 tool224,
 tool225,
 tool226,
 tool227,
 tool228,
 tool229,
 tool230,
 tool231,
 tool232,
 tool233,
 tool234,
 tool235,
 tool236,
 tool237,
 tool238,
 tool239,
 tool240,
 tool241,
 tool242,
 tool243,
 tool244,
 tool245,
 tool246,
 tool247,
 tool248,
 tool249,
 tool250,
 tool251,
 tool252,
 tool253,
 tool254,
 tool255,
 tool256,
 tool257,
 tool258,
 tool259,
 tool260,
 tool261,
 tool262,
 tool263,
 tool264,
 tool265,
 tool266,
 tool267,
 tool268,
 tool269,
 tool270,
 tool271,
 tool272,
 tool273,
 tool274,
 tool275,
 tool276,
 tool277,
 tool278,
 tool279,
 tool280,
 tool281,
 tool282,
 tool283,
 tool284,
 tool285,
 tool286,
 tool287,
 tool288,
 tool289,
 tool290,
 tool291,
 tool292,
 tool293,
 tool294,
 tool295,
 tool296,
 tool297,
 tool298,
 tool299,
 tool300,
 tool301,
 tool302,
 tool303,
 tool304,
 tool305,
 tool306,
 tool307,
 tool308,
 tool309,
 tool310,
 tool311,
 tool312,
 tool313,
 tool314,
 tool315,
 tool316,
 tool317,
 tool318,
 tool319,
 tool320,
 tool321,
 tool322,
 tool323,
 tool324,
 tool325,
 tool326,
 tool327,
 tool328,
 tool329,
 tool330,
 tool331,
 tool332,
];
