/**
 * Triggers a browser "Save As" for generated bytes. Framework-free so it's
 * usable from any tool (first needed by File Base64 Conversion's decode
 * direction; also offered to the WYSIWYG/Markdown Workspace export buttons).
 */
export function downloadFile(bytes: Uint8Array | Blob, filename: string, mimeType = 'application/octet-stream'): void {
  const blob = bytes instanceof Blob ? bytes : new Blob([new Uint8Array(bytes)], { type: mimeType });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement('a');
  anchor.href = url;
  anchor.download = filename;
  anchor.click();
  URL.revokeObjectURL(url);
}
