import type { ToolMetadata } from "@dude/domain/shared/models/tool-metadata.model";
export const manifest: ToolMetadata = {
    id: 'binary-structure-inspector',
    title: 'Binary Structure Inspector',
    description: 'Parses an uploaded file against a user-defined sequence of typed fields (integers, floats, fixed-length strings, chosen endianness) into a table of offsets and decoded values.',
    category: 'developer',
    keywords: ['struct', 'binary structure', 'c struct', 'kaitai', 'parse binary', 'field layout'],
    route: '/tools/binary-structure-inspector',
    status: 'verified',
    verification: {
        propertyTested: true,
        summary: 'Fuzzed struct parsing over generated byte buffers and field definitions, checking no throws and consumed-byte bounds.',
    },
    persistence: { input: 'none', preferences: 'local' },
    io: { accepts: ['file'], produces: ['table'] }
};
