// Generated by scripts/generate-theme-css.mjs from apps/web/src/styles/theme/theme-tokens.json - generated, never hand-edit.

export const THEME_TOKENS_DATA = {
  "axes": {
    "theme": {
      "attr": "data-theme",
      "values": [
        "dark",
        "light"
      ],
      "default": "dark",
      "labels": {
        "dark": "Dark",
        "light": "Light"
      }
    },
    "contrast": {
      "attr": "data-contrast",
      "values": [
        "standard",
        "high"
      ],
      "default": "standard",
      "labels": {
        "standard": "Standard",
        "high": "High"
      }
    },
    "accent": {
      "attr": "data-accent",
      "values": [
        "cyan",
        "blue",
        "violet",
        "green",
        "amber",
        "magenta"
      ],
      "default": "cyan",
      "labels": {
        "cyan": "Cyan",
        "blue": "Blue",
        "violet": "Violet",
        "green": "Green",
        "amber": "Amber",
        "magenta": "Magenta"
      }
    },
    "catset": {
      "attr": "data-catset",
      "values": [
        "vivid",
        "soft",
        "cvd"
      ],
      "default": "vivid",
      "labels": {
        "vivid": "Vivid",
        "soft": "Soft",
        "cvd": "Color-blind safe"
      }
    },
    "semantic": {
      "attr": "data-semantic",
      "values": [
        "standard",
        "cvd"
      ],
      "default": "standard",
      "labels": {
        "standard": "Standard",
        "cvd": "Color-blind safe"
      }
    },
    "density": {
      "attr": "data-density",
      "values": [
        "compact",
        "comfortable",
        "ultra"
      ],
      "default": "compact",
      "labels": {
        "compact": "Compact",
        "comfortable": "Comfortable",
        "ultra": "Ultra-compact"
      }
    },
    "uiSize": {
      "attr": "data-ui-size",
      "values": [
        "default",
        "small",
        "large"
      ],
      "default": "default",
      "labels": {
        "default": "Default",
        "small": "Small",
        "large": "Large"
      }
    },
    "monoSize": {
      "attr": "data-mono-size",
      "values": [
        "default",
        "small",
        "large"
      ],
      "default": "default",
      "labels": {
        "default": "Default",
        "small": "Small",
        "large": "Large"
      }
    },
    "ligatures": {
      "attr": "data-ligatures",
      "values": [
        "on",
        "off"
      ],
      "default": "on",
      "labels": {
        "on": "On",
        "off": "Off"
      }
    },
    "motion": {
      "attr": "data-motion",
      "values": [
        "allow",
        "reduce"
      ],
      "default": "allow",
      "labels": {
        "allow": "Allow",
        "reduce": "Reduce"
      }
    }
  },
  "sizeSteps": {
    "default": "1",
    "small": "0.9167",
    "large": "1.1667"
  },
  "bases": {
    "dark": {
      "standard": {
        "bg": "#0a0e14",
        "panel": "#10151d",
        "panel-elevated": "#161c26",
        "border": "#232b38",
        "text": "#e6e9ef",
        "text-muted": "#8b93a3",
        "focus-width": "2px",
        "color-scheme": "dark",
        "scrim": "#000000",
        "wash-pct": "8%",
        "tint-toward": "white",
        "tint-pct": "20%"
      },
      "high": {
        "bg": "#000000",
        "panel": "#0a0d12",
        "panel-elevated": "#11151c",
        "border": "#8a94a6",
        "text": "#ffffff",
        "text-muted": "#c3cad6",
        "focus-width": "3px",
        "color-scheme": "dark",
        "scrim": "#000000",
        "wash-pct": "6%",
        "tint-toward": "white",
        "tint-pct": "20%"
      }
    },
    "light": {
      "standard": {
        "bg": "#eef1f5",
        "panel": "#ffffff",
        "panel-elevated": "#f6f8fc",
        "border": "#c5cdd8",
        "text": "#111827",
        "text-muted": "#475569",
        "focus-width": "2px",
        "color-scheme": "light",
        "scrim": "#0f172a",
        "wash-pct": "8%",
        "tint-toward": "black",
        "tint-pct": "20%"
      },
      "high": {
        "bg": "#ffffff",
        "panel": "#ffffff",
        "panel-elevated": "#f3f5f9",
        "border": "#4f596a",
        "text": "#000000",
        "text-muted": "#37404f",
        "focus-width": "3px",
        "color-scheme": "light",
        "scrim": "#0f172a",
        "wash-pct": "6%",
        "tint-toward": "black",
        "tint-pct": "20%"
      }
    }
  },
  "accents": {
    "cyan": {
      "dark": {
        "standard": {
          "accent": "#38d8ff",
          "on-accent": "#0a0e14"
        },
        "high": {
          "accent": "#42daff",
          "on-accent": "#000000"
        }
      },
      "light": {
        "standard": {
          "accent": "#035e91",
          "on-accent": "#ffffff"
        },
        "high": {
          "accent": "#034c74",
          "on-accent": "#ffffff"
        }
      }
    },
    "blue": {
      "dark": {
        "standard": {
          "accent": "#80b0ff",
          "on-accent": "#0a0e14"
        },
        "high": {
          "accent": "#b3cfff",
          "on-accent": "#000000"
        }
      },
      "light": {
        "standard": {
          "accent": "#003fa3",
          "on-accent": "#ffffff"
        },
        "high": {
          "accent": "#003385",
          "on-accent": "#ffffff"
        }
      }
    },
    "violet": {
      "dark": {
        "standard": {
          "accent": "#a280ff",
          "on-accent": "#0a0e14"
        },
        "high": {
          "accent": "#baa1ff",
          "on-accent": "#000000"
        }
      },
      "light": {
        "standard": {
          "accent": "#4900b8",
          "on-accent": "#ffffff"
        },
        "high": {
          "accent": "#4500ae",
          "on-accent": "#ffffff"
        }
      }
    },
    "green": {
      "dark": {
        "standard": {
          "accent": "#66ff94",
          "on-accent": "#0a0e14"
        },
        "high": {
          "accent": "#70ff9b",
          "on-accent": "#000000"
        }
      },
      "light": {
        "standard": {
          "accent": "#006627",
          "on-accent": "#ffffff"
        },
        "high": {
          "accent": "#005420",
          "on-accent": "#ffffff"
        }
      }
    },
    "amber": {
      "dark": {
        "standard": {
          "accent": "#ffc042",
          "on-accent": "#0a0e14"
        },
        "high": {
          "accent": "#ffc34c",
          "on-accent": "#000000"
        }
      },
      "light": {
        "standard": {
          "accent": "#993d00",
          "on-accent": "#ffffff"
        },
        "high": {
          "accent": "#7b3100",
          "on-accent": "#ffffff"
        }
      }
    },
    "magenta": {
      "dark": {
        "standard": {
          "accent": "#ff42ba",
          "on-accent": "#0a0e14"
        },
        "high": {
          "accent": "#ff85d2",
          "on-accent": "#000000"
        }
      },
      "light": {
        "standard": {
          "accent": "#a30067",
          "on-accent": "#ffffff"
        },
        "high": {
          "accent": "#8b0058",
          "on-accent": "#ffffff"
        }
      }
    }
  },
  "categorySets": {
    "vivid": {
      "dark": {
        "standard": {
          "data": "#22d3ee",
          "text": "#a3e635",
          "encoding": "#fb923c",
          "security": "#f97bf7",
          "date-time": "#a78bfa",
          "web": "#81b9fe",
          "developer": "#34d399",
          "documents": "#f472b6"
        },
        "high": {
          "data": "#2bd5ef",
          "text": "#a7e73e",
          "encoding": "#fb9846",
          "security": "#f985f8",
          "date-time": "#b59dfb",
          "web": "#b3d5fe",
          "developer": "#3cd59d",
          "documents": "#f585c0"
        }
      },
      "light": {
        "standard": {
          "data": "#0c6179",
          "text": "#3e640c",
          "encoding": "#944008",
          "security": "#9d1685",
          "date-time": "#5b21b6",
          "web": "#4338ca",
          "developer": "#03654a",
          "documents": "#a61f51"
        },
        "high": {
          "data": "#0a5064",
          "text": "#32510a",
          "encoding": "#7c3607",
          "security": "#891374",
          "date-time": "#571fad",
          "web": "#3f34c3",
          "developer": "#02523c",
          "documents": "#911b47"
        }
      }
    },
    "soft": {
      "dark": {
        "standard": {
          "data": "#3fb8ca",
          "text": "#9acd47",
          "encoding": "#d3935f",
          "security": "#e090de",
          "date-time": "#ad9be4",
          "web": "#9bbbe4",
          "developer": "#3bc995",
          "documents": "#dd83b2"
        },
        "high": {
          "data": "#47bbcc",
          "text": "#9ecf4f",
          "encoding": "#d79c6d",
          "security": "#e298e0",
          "date-time": "#b4a3e6",
          "web": "#c3d6ef",
          "developer": "#43cb99",
          "documents": "#e191bb"
        }
      },
      "light": {
        "standard": {
          "data": "#206274",
          "text": "#45641b",
          "encoding": "#844b24",
          "security": "#942981",
          "date-time": "#6431b4",
          "web": "#4d43cb",
          "developer": "#195c4a",
          "documents": "#a02c57"
        },
        "high": {
          "data": "#1a505f",
          "text": "#375016",
          "encoding": "#6f3f1e",
          "security": "#822471",
          "date-time": "#5f2fab",
          "web": "#3f35c0",
          "developer": "#175343",
          "documents": "#89264a"
        }
      }
    },
    "cvd": {
      "dark": {
        "standard": {
          "data": "#50ecec",
          "text": "#cce494",
          "encoding": "#f4b858",
          "security": "#d86cc4",
          "date-time": "#9884fc",
          "web": "#84bcfc",
          "developer": "#00ac60",
          "documents": "#f45898"
        },
        "high": {
          "data": "#00fcb9",
          "text": "#92f33d",
          "encoding": "#fff18e",
          "security": "#ea7ac3",
          "date-time": "#bbc1fc",
          "web": "#2aa7ff",
          "developer": "#02c83d",
          "documents": "#fdbfdf"
        }
      },
      "light": {
        "standard": {
          "data": "#0058a0",
          "text": "#4c602c",
          "encoding": "#861600",
          "security": "#a61664",
          "date-time": "#561ea6",
          "web": "#540cd6",
          "developer": "#024e30",
          "documents": "#880470"
        },
        "high": {
          "data": "#002d84",
          "text": "#4a5900",
          "encoding": "#5c2312",
          "security": "#512547",
          "date-time": "#682ac4",
          "web": "#2022ff",
          "developer": "#045f42",
          "documents": "#8c2a7b"
        }
      }
    }
  },
  "semanticSets": {
    "standard": {
      "dark": {
        "standard": {
          "error": "#ff5757",
          "warning": "#d99a00",
          "success": "#46e05a",
          "info": "#4294ff",
          "busy": "#c966ff",
          "offline": "#8c97a8"
        },
        "high": {
          "error": "#ff8686",
          "warning": "#e3a100",
          "success": "#4fe162",
          "info": "#6fadff",
          "busy": "#e8bfff",
          "offline": "#a1aab8"
        }
      },
      "light": {
        "standard": {
          "error": "#a91b1b",
          "warning": "#6f5700",
          "success": "#106810",
          "info": "#134dce",
          "busy": "#8e1aaf",
          "offline": "#4f5b6d"
        },
        "high": {
          "error": "#961a18",
          "warning": "#594600",
          "success": "#0d550d",
          "info": "#1143b3",
          "busy": "#7c1799",
          "offline": "#424c5b"
        }
      }
    },
    "cvd": {
      "dark": {
        "standard": {
          "error": "#fe594d",
          "warning": "#d9d026",
          "success": "#6198e0",
          "info": "#7fe8fd",
          "busy": "#ffa6d5",
          "offline": "#8c97a8"
        },
        "high": {
          "error": "#ff8177",
          "warning": "#ddd12c",
          "success": "#7aabf0",
          "info": "#02bdd2",
          "busy": "#d997fe",
          "offline": "#a1aab8"
        }
      },
      "light": {
        "standard": {
          "error": "#7b0222",
          "warning": "#6f5701",
          "success": "#194fcc",
          "info": "#003047",
          "busy": "#712484",
          "offline": "#4f5b6d"
        },
        "high": {
          "error": "#6c021e",
          "warning": "#5f4b00",
          "success": "#023dc7",
          "info": "#4e4e74",
          "busy": "#5e296b",
          "offline": "#424c5b"
        }
      }
    }
  },
  "density": {
    "compact": {
      "spacing": "0.25rem",
      "control-h": "1.75rem",
      "row-h": "1.75rem",
      "radius": "0.25rem",
      "text-ui": "0.8125rem",
      "text-ui-sm": "0.75rem",
      "text-ui-xs": "0.6875rem",
      "space-micro": "0.25rem",
      "space-normal": "0.5rem",
      "space-panel": "0.75rem",
      "space-major": "1rem",
      "space-exceptional": "1.5rem"
    },
    "comfortable": {
      "spacing": "0.3125rem",
      "control-h": "2rem",
      "row-h": "2rem",
      "radius": "0.3125rem",
      "text-ui": "0.875rem",
      "text-ui-sm": "0.8125rem",
      "text-ui-xs": "0.75rem",
      "space-micro": "0.3125rem",
      "space-normal": "0.625rem",
      "space-panel": "1rem",
      "space-major": "1.25rem",
      "space-exceptional": "2rem"
    },
    "ultra": {
      "spacing": "0.1875rem",
      "control-h": "1.5rem",
      "row-h": "1.5rem",
      "radius": "0.1875rem",
      "text-ui": "0.75rem",
      "text-ui-sm": "0.6875rem",
      "text-ui-xs": "0.6875rem",
      "space-micro": "0.1875rem",
      "space-normal": "0.375rem",
      "space-panel": "0.5rem",
      "space-major": "0.75rem",
      "space-exceptional": "1.125rem"
    }
  },
  "fonts": {
    "ui": [
      {
        "id": "system",
        "label": "System UI",
        "stack": "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif"
      },
      {
        "id": "segoe",
        "label": "Segoe UI",
        "stack": "'Segoe UI Variable Text', 'Segoe UI', system-ui, sans-serif"
      },
      {
        "id": "inter",
        "label": "Inter (if installed)",
        "stack": "Inter, 'Inter Variable', ui-sans-serif, system-ui, sans-serif"
      },
      {
        "id": "helvetica",
        "label": "Helvetica / Arial",
        "stack": "'Helvetica Neue', Helvetica, Arial, 'Liberation Sans', sans-serif"
      },
      {
        "id": "verdana",
        "label": "Verdana (wide)",
        "stack": "Verdana, 'DejaVu Sans', 'Bitstream Vera Sans', sans-serif"
      },
      {
        "id": "atkinson",
        "label": "Atkinson Hyperlegible (if installed)",
        "stack": "'Atkinson Hyperlegible', 'Atkinson Hyperlegible Next', ui-sans-serif, system-ui, sans-serif"
      }
    ],
    "mono": [
      {
        "id": "default",
        "label": "JetBrains Mono / Fira Code",
        "stack": "'JetBrains Mono', 'Fira Code', ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace"
      },
      {
        "id": "cascadia",
        "label": "Cascadia Code",
        "stack": "'Cascadia Code', 'Cascadia Mono', Consolas, ui-monospace, monospace"
      },
      {
        "id": "consolas",
        "label": "Consolas",
        "stack": "Consolas, 'Lucida Console', 'Courier New', monospace"
      },
      {
        "id": "system",
        "label": "System monospace",
        "stack": "ui-monospace, 'SFMono-Regular', Menlo, Monaco, Consolas, 'Liberation Mono', monospace"
      },
      {
        "id": "plex",
        "label": "IBM Plex Mono (if installed)",
        "stack": "'IBM Plex Mono', ui-monospace, Consolas, monospace"
      },
      {
        "id": "source",
        "label": "Source Code Pro (if installed)",
        "stack": "'Source Code Pro', ui-monospace, Consolas, monospace"
      }
    ],
    "defaultUi": "system",
    "defaultMono": "default"
  }
} as const;
