import type { ToolDefinition } from '../../shared/models/tool-definition.model';

export const manifest: ToolDefinition = {
  id: 'jwks-to-pem',
  title: 'JWKS → Public Keys',
  shortTitle: 'JWKS → PEM',
  description: 'Converts JWKS keys to PEM (SPKI) or raw JWK for use outside the browser.',
  category: 'security',
  keywords: ['jwks', 'jwk', 'pem', 'spki', 'public key', 'convert', 'export'],
  route: '/tools/jwks-to-pem',
  load: () => import('./jwks-to-pem').then((m) => m.JwksToPem),
  status: 'verified',
  verification: {
    crossChecked: ["Node's crypto (generateKeyPairSync + createPublicKey)"],
    summary: 'A JWK generated by Node\'s crypto module (not jose) converts to a PEM that Node\'s own createPublicKey re-imports to an identical modulus/exponent.',
  },
  consequenceClass: ['crypto'],
  persistence: { input: 'none', preferences: 'local' },
  io: { accepts: ['text', 'json'], produces: ['text'] },
};
