import { describe, expect, it } from 'vitest';
import { generateAsymmetricKeyPair } from '../asymmetric-key-generator/asymmetric-keygen-logic';
import { CsrSubjectField, generateCsr, inspectCsr } from './csr-logic';

async function rsaPrivateKeyPem(): Promise<string> {
  const pair = await generateAsymmetricKeyPair({ family: 'rsa', modulusLength: 2048 });
  return pair.privateKeyPem;
}

describe('csr-logic', () => {
  it('generates a CSR PEM from subject fields and a jose-generated PKCS8 RSA private key', async () => {
    const privateKeyPem = await rsaPrivateKeyPem();
    const fields: CsrSubjectField[] = [
      { shortName: 'CN', value: 'example.com' },
      { shortName: 'O', value: 'Example Org' },
    ];

    const result = generateCsr(fields, privateKeyPem);
    expect(result.ok).toBe(true);
    if (!result.ok) throw new Error(result.error);
    expect(result.csrPem).toMatch(/-----BEGIN CERTIFICATE REQUEST-----/);
  });

  it('rejects generation with no non-empty subject fields', async () => {
    const privateKeyPem = await rsaPrivateKeyPem();
    const result = generateCsr([{ shortName: 'CN', value: '' }], privateKeyPem);
    expect(result.ok).toBe(false);
  });

  it('rejects generation with a malformed private key', () => {
    const result = generateCsr([{ shortName: 'CN', value: 'example.com' }], 'not a real key');
    expect(result.ok).toBe(false);
  });

  it('round-trips: a generated CSR inspects back with the same subject and a valid signature', async () => {
    const privateKeyPem = await rsaPrivateKeyPem();
    const fields: CsrSubjectField[] = [
      { shortName: 'CN', value: 'example.com' },
      { shortName: 'C', value: 'US' },
    ];
    const generated = generateCsr(fields, privateKeyPem);
    if (!generated.ok) throw new Error(generated.error);

    const inspected = inspectCsr(generated.csrPem);
    expect(inspected.ok).toBe(true);
    if (!inspected.ok) throw new Error(inspected.error);
    expect(inspected.csr.signatureValid).toBe(true);
    expect(inspected.csr.publicKeyBits).toBe(2048);
    expect(inspected.csr.subject).toEqual(
      expect.arrayContaining([
        expect.objectContaining({ shortName: 'CN', value: 'example.com' }),
        expect.objectContaining({ shortName: 'C', value: 'US' }),
      ]),
    );
  });

  it('rejects inspecting a malformed CSR PEM', () => {
    const result = inspectCsr('not a csr');
    expect(result.ok).toBe(false);
  });

  it('rejects an EC/Ed25519 private key for CSR signing', async () => {
    const pair = await generateAsymmetricKeyPair({ family: 'ed25519' });
    const result = generateCsr([{ shortName: 'CN', value: 'example.com' }], pair.privateKeyPem);
    expect(result.ok).toBe(false);
    expect(result.ok || result.error).toMatch(/rsa/i);
  });

  // DUDE_PRD.md §21 Phase 23 Item 3 -- a real CSR generated by `openssl req -newkey rsa:2048`
  // (`openssl req -subj "/C=US/ST=California/L=San Francisco/O=DUDE Test/CN=dude-test.example.com"`),
  // whose subject/key-size/signature-validity `openssl req -in csr.pem -noout -text` independently
  // confirms, not a CSR DUDE generated and inspected with its own code both ways.
  it('parses a real openssl-generated CSR and matches its subject/key size/signature validity', () => {
    const opensslCsrPem = `-----BEGIN CERTIFICATE REQUEST-----
MIICszCCAZsCAQAwbjELMAkGA1UEBhMCVVMxEzARBgNVBAgMCkNhbGlmb3JuaWEx
FjAUBgNVBAcMDVNhbiBGcmFuY2lzY28xEjAQBgNVBAoMCURVREUgVGVzdDEeMBwG
A1UEAwwVZHVkZS10ZXN0LmV4YW1wbGUuY29tMIIBIjANBgkqhkiG9w0BAQEFAAOC
AQ8AMIIBCgKCAQEAl+7ycFzGiKO/VM4Z8ug4hbvvu7bPhxTp9RK9cp03sVPgZvVO
C0PMzPAgVWssaZ0lHiyu4dKiX4tjOOcG9OpXnBidfGAnGYtiAYS/yAuqHFShej7I
buaINvWrqH3NmvPrk/m2jVg7XFpeStNiZRXxiaaaO7RxeLB/rOB8ItGaC20Imzps
z/nnjWryYUxyN6ajIQ59+pF0uoWNwx2QfTg4ILaHtoAkIjQIx5eLz4IfuGHzHzXg
J93IYmgdWLDfIhuHI42fSrPNPwJfpazurruKzsAOJUKErKT7g81UabST2P5gPQtg
fIT2UNesbUjbPOADbRfaw8G1uERpuNZQ3F0eMwIDAQABoAAwDQYJKoZIhvcNAQEL
BQADggEBADUnvyUh+8AulOAfdsnxut0ME8sKlrzejffsnq85PDbPtpY53VtVWYUK
XE75j69S3R/LwZVvMr6dt1G+J2VXzqICF1emaqyFIB6u+bmx3l5BgC4iOm5M8rcB
KRbxjq1kMBEGIWvSmzJZBA6v8kkhzPALvmG/EihP4cqL9rTPtWxj26Cjjji7J4dv
uIcpXTYJzGEp7g9ddX7iapz60WG9zxO0/HJGW7/PnLG0paZLpkPlnW7kPlUadnJE
sdVyJjFGCQz2Y7taSI3CYURU67PU6JdIcRrJyUg5jJgJ2Kx3FpkwdlTx9G0MiBcF
M1BMAWtpv5Ye+p6NzELzxu5vO8rGe1I=
-----END CERTIFICATE REQUEST-----`;

    const inspected = inspectCsr(opensslCsrPem);
    expect(inspected.ok).toBe(true);
    if (!inspected.ok) return;

    // openssl req -in csr.pem -noout -text: "Subject: C=US, ST=California, L=San Francisco,
    // O=DUDE Test, CN=dude-test.example.com" and "Public-Key: (2048 bit)".
    expect(inspected.csr.signatureValid).toBe(true);
    expect(inspected.csr.publicKeyBits).toBe(2048);
    expect(inspected.csr.subject).toEqual([
      expect.objectContaining({ shortName: 'C', value: 'US' }),
      expect.objectContaining({ shortName: 'ST', value: 'California' }),
      expect.objectContaining({ shortName: 'L', value: 'San Francisco' }),
      expect.objectContaining({ shortName: 'O', value: 'DUDE Test' }),
      expect.objectContaining({ shortName: 'CN', value: 'dude-test.example.com' }),
    ]);
  });
});
