export type ErrorCodeCategory = 'windows' | 'posix' | 'linux-signals' | 'sql' | 'tls' | 'dns';

export interface ErrorCodeCategoryMeta {
  readonly id: ErrorCodeCategory;
  readonly label: string;
}

export const ERROR_CODE_CATEGORIES: readonly ErrorCodeCategoryMeta[] = [
  { id: 'windows', label: 'Windows / Win32 / HRESULT' },
  { id: 'posix', label: 'POSIX errno' },
  { id: 'linux-signals', label: 'Linux signals' },
  { id: 'sql', label: 'SQL (SQLSTATE / vendor codes)' },
  { id: 'tls', label: 'TLS alerts' },
  { id: 'dns', label: 'DNS response codes' },
];

export interface ErrorCodeEntry {
  readonly category: ErrorCodeCategory;
  readonly code: string;
  readonly name: string;
  readonly description: string;
}

export const ERROR_CODES: readonly ErrorCodeEntry[] = [
  // Windows / Win32 / HRESULT
  { category: 'windows', code: '0x00000000', name: 'S_OK', description: 'Operation successful.' },
  { category: 'windows', code: '0x00000001', name: 'S_FALSE', description: 'Operation successful, but returned a false/negative result.' },
  { category: 'windows', code: '0x80004001', name: 'E_NOTIMPL', description: 'Not implemented.' },
  { category: 'windows', code: '0x80004002', name: 'E_NOINTERFACE', description: 'No such interface supported.' },
  { category: 'windows', code: '0x80004003', name: 'E_POINTER', description: 'Invalid pointer.' },
  { category: 'windows', code: '0x80004004', name: 'E_ABORT', description: 'Operation aborted.' },
  { category: 'windows', code: '0x80004005', name: 'E_FAIL', description: 'Unspecified failure.' },
  { category: 'windows', code: '0x8000FFFF', name: 'E_UNEXPECTED', description: 'Catastrophic failure.' },
  { category: 'windows', code: '0x80070005', name: 'E_ACCESSDENIED', description: 'General access denied error.' },
  { category: 'windows', code: '0x8007000E', name: 'E_OUTOFMEMORY', description: 'Ran out of memory.' },
  { category: 'windows', code: '0x80070057', name: 'E_INVALIDARG', description: 'One or more arguments are invalid.' },
  { category: 'windows', code: '2', name: 'ERROR_FILE_NOT_FOUND', description: 'The system cannot find the file specified.' },
  { category: 'windows', code: '3', name: 'ERROR_PATH_NOT_FOUND', description: 'The system cannot find the path specified.' },
  { category: 'windows', code: '5', name: 'ERROR_ACCESS_DENIED', description: 'Access is denied.' },
  { category: 'windows', code: '6', name: 'ERROR_INVALID_HANDLE', description: 'The handle is invalid.' },
  { category: 'windows', code: '8', name: 'ERROR_NOT_ENOUGH_MEMORY', description: 'Not enough storage is available to process this command.' },
  { category: 'windows', code: '18', name: 'ERROR_NO_MORE_FILES', description: 'There are no more files.' },
  { category: 'windows', code: '32', name: 'ERROR_SHARING_VIOLATION', description: 'The process cannot access the file because it is being used by another process.' },
  { category: 'windows', code: '87', name: 'ERROR_INVALID_PARAMETER', description: 'The parameter is incorrect.' },
  { category: 'windows', code: '122', name: 'ERROR_INSUFFICIENT_BUFFER', description: 'The data area passed to a system call is too small.' },
  { category: 'windows', code: '126', name: 'ERROR_MOD_NOT_FOUND', description: 'The specified module could not be found.' },
  { category: 'windows', code: '127', name: 'ERROR_PROC_NOT_FOUND', description: 'The specified procedure could not be found.' },
  { category: 'windows', code: '183', name: 'ERROR_ALREADY_EXISTS', description: 'Cannot create a file when that file already exists.' },
  { category: 'windows', code: '995', name: 'ERROR_OPERATION_ABORTED', description: 'The I/O operation has been aborted because of either a thread exit or an application request.' },
  { category: 'windows', code: '997', name: 'ERROR_IO_PENDING', description: 'Overlapped I/O operation is in progress.' },
  { category: 'windows', code: '1168', name: 'ERROR_NOT_FOUND', description: 'Element not found.' },
  { category: 'windows', code: '1460', name: 'ERROR_TIMEOUT', description: 'This operation returned because the timeout period expired.' },
  { category: 'windows', code: '1722', name: 'RPC_S_SERVER_UNAVAILABLE', description: 'The RPC server is unavailable.' },
  { category: 'windows', code: '0x800706BA', name: 'RPC_S_SERVER_UNAVAILABLE (HRESULT)', description: 'HRESULT form of Win32 error 1722 — the RPC server is unavailable.' },
  { category: 'windows', code: '0x80072EE7', name: 'WININET_E_NAME_NOT_RESOLVED', description: 'The server name or address could not be resolved (DNS lookup failed).' },
  { category: 'windows', code: '0x80072EFD', name: 'WININET_E_CANNOT_CONNECT', description: 'A connection with the server could not be established.' },
  { category: 'windows', code: '0x8009030C', name: 'SEC_E_LOGON_DENIED', description: 'The logon attempt failed (SSPI).' },

  // POSIX errno
  { category: 'posix', code: '1', name: 'EPERM', description: 'Operation not permitted.' },
  { category: 'posix', code: '2', name: 'ENOENT', description: 'No such file or directory.' },
  { category: 'posix', code: '3', name: 'ESRCH', description: 'No such process.' },
  { category: 'posix', code: '4', name: 'EINTR', description: 'Interrupted system call.' },
  { category: 'posix', code: '5', name: 'EIO', description: 'Input/output error.' },
  { category: 'posix', code: '6', name: 'ENXIO', description: 'No such device or address.' },
  { category: 'posix', code: '7', name: 'E2BIG', description: 'Argument list too long.' },
  { category: 'posix', code: '8', name: 'ENOEXEC', description: 'Exec format error.' },
  { category: 'posix', code: '9', name: 'EBADF', description: 'Bad file descriptor.' },
  { category: 'posix', code: '10', name: 'ECHILD', description: 'No child processes.' },
  { category: 'posix', code: '11', name: 'EAGAIN / EWOULDBLOCK', description: 'Resource temporarily unavailable — the operation would block.' },
  { category: 'posix', code: '12', name: 'ENOMEM', description: 'Cannot allocate memory.' },
  { category: 'posix', code: '13', name: 'EACCES', description: 'Permission denied.' },
  { category: 'posix', code: '14', name: 'EFAULT', description: 'Bad address.' },
  { category: 'posix', code: '16', name: 'EBUSY', description: 'Device or resource busy.' },
  { category: 'posix', code: '17', name: 'EEXIST', description: 'File exists.' },
  { category: 'posix', code: '18', name: 'EXDEV', description: 'Invalid cross-device link.' },
  { category: 'posix', code: '19', name: 'ENODEV', description: 'No such device.' },
  { category: 'posix', code: '20', name: 'ENOTDIR', description: 'Not a directory.' },
  { category: 'posix', code: '21', name: 'EISDIR', description: 'Is a directory.' },
  { category: 'posix', code: '22', name: 'EINVAL', description: 'Invalid argument.' },
  { category: 'posix', code: '23', name: 'ENFILE', description: 'Too many open files in system.' },
  { category: 'posix', code: '24', name: 'EMFILE', description: 'Too many open files.' },
  { category: 'posix', code: '25', name: 'ENOTTY', description: 'Inappropriate ioctl for device.' },
  { category: 'posix', code: '27', name: 'EFBIG', description: 'File too large.' },
  { category: 'posix', code: '28', name: 'ENOSPC', description: 'No space left on device.' },
  { category: 'posix', code: '29', name: 'ESPIPE', description: 'Illegal seek.' },
  { category: 'posix', code: '30', name: 'EROFS', description: 'Read-only file system.' },
  { category: 'posix', code: '31', name: 'EMLINK', description: 'Too many links.' },
  { category: 'posix', code: '32', name: 'EPIPE', description: 'Broken pipe.' },
  { category: 'posix', code: '36', name: 'ENAMETOOLONG', description: 'File name too long.' },
  { category: 'posix', code: '38', name: 'ENOSYS', description: 'Function not implemented.' },
  { category: 'posix', code: '39', name: 'ENOTEMPTY', description: 'Directory not empty.' },
  { category: 'posix', code: '40', name: 'ELOOP', description: 'Too many levels of symbolic links.' },
  { category: 'posix', code: '88', name: 'ENOTSOCK', description: 'Socket operation on non-socket.' },
  { category: 'posix', code: '90', name: 'EMSGSIZE', description: 'Message too long.' },
  { category: 'posix', code: '95', name: 'EOPNOTSUPP', description: 'Operation not supported (on transport endpoint).' },
  { category: 'posix', code: '97', name: 'EAFNOSUPPORT', description: 'Address family not supported by protocol.' },
  { category: 'posix', code: '98', name: 'EADDRINUSE', description: 'Address already in use.' },
  { category: 'posix', code: '99', name: 'EADDRNOTAVAIL', description: 'Cannot assign requested address.' },
  { category: 'posix', code: '100', name: 'ENETDOWN', description: 'Network is down.' },
  { category: 'posix', code: '101', name: 'ENETUNREACH', description: 'Network is unreachable.' },
  { category: 'posix', code: '104', name: 'ECONNRESET', description: 'Connection reset by peer.' },
  { category: 'posix', code: '105', name: 'ENOBUFS', description: 'No buffer space available.' },
  { category: 'posix', code: '106', name: 'EISCONN', description: 'Transport endpoint is already connected.' },
  { category: 'posix', code: '107', name: 'ENOTCONN', description: 'Transport endpoint is not connected.' },
  { category: 'posix', code: '110', name: 'ETIMEDOUT', description: 'Connection timed out.' },
  { category: 'posix', code: '111', name: 'ECONNREFUSED', description: 'Connection refused.' },
  { category: 'posix', code: '113', name: 'EHOSTUNREACH', description: 'No route to host.' },
  { category: 'posix', code: '114', name: 'EALREADY', description: 'Operation already in progress.' },
  { category: 'posix', code: '115', name: 'EINPROGRESS', description: 'Operation now in progress.' },
  { category: 'posix', code: '116', name: 'ESTALE', description: 'Stale file handle (NFS).' },
  { category: 'posix', code: '122', name: 'EDQUOT', description: 'Disk quota exceeded.' },

  // Linux signals
  { category: 'linux-signals', code: '1', name: 'SIGHUP', description: 'Hangup detected on controlling terminal, or death of controlling process.' },
  { category: 'linux-signals', code: '2', name: 'SIGINT', description: 'Interrupt from keyboard (Ctrl+C).' },
  { category: 'linux-signals', code: '3', name: 'SIGQUIT', description: 'Quit from keyboard, with core dump.' },
  { category: 'linux-signals', code: '4', name: 'SIGILL', description: 'Illegal instruction.' },
  { category: 'linux-signals', code: '5', name: 'SIGTRAP', description: 'Trace/breakpoint trap.' },
  { category: 'linux-signals', code: '6', name: 'SIGABRT / SIGIOT', description: 'Abort signal from abort(3).' },
  { category: 'linux-signals', code: '7', name: 'SIGBUS', description: 'Bus error — bad memory access.' },
  { category: 'linux-signals', code: '8', name: 'SIGFPE', description: 'Floating-point exception.' },
  { category: 'linux-signals', code: '9', name: 'SIGKILL', description: 'Kill signal — cannot be caught, blocked, or ignored.' },
  { category: 'linux-signals', code: '10', name: 'SIGUSR1', description: 'User-defined signal 1.' },
  { category: 'linux-signals', code: '11', name: 'SIGSEGV', description: 'Invalid memory reference (segmentation fault).' },
  { category: 'linux-signals', code: '12', name: 'SIGUSR2', description: 'User-defined signal 2.' },
  { category: 'linux-signals', code: '13', name: 'SIGPIPE', description: 'Broken pipe — write to a pipe with no readers.' },
  { category: 'linux-signals', code: '14', name: 'SIGALRM', description: 'Timer signal from alarm(2).' },
  { category: 'linux-signals', code: '15', name: 'SIGTERM', description: 'Termination signal — the default/graceful kill signal.' },
  { category: 'linux-signals', code: '17', name: 'SIGCHLD', description: 'Child stopped or terminated.' },
  { category: 'linux-signals', code: '18', name: 'SIGCONT', description: 'Continue if stopped.' },
  { category: 'linux-signals', code: '19', name: 'SIGSTOP', description: 'Stop process — cannot be caught, blocked, or ignored.' },
  { category: 'linux-signals', code: '20', name: 'SIGTSTP', description: 'Stop typed at terminal (Ctrl+Z).' },
  { category: 'linux-signals', code: '21', name: 'SIGTTIN', description: 'Terminal input for background process.' },
  { category: 'linux-signals', code: '22', name: 'SIGTTOU', description: 'Terminal output for background process.' },
  { category: 'linux-signals', code: '23', name: 'SIGURG', description: 'Urgent condition on socket.' },
  { category: 'linux-signals', code: '24', name: 'SIGXCPU', description: 'CPU time limit exceeded.' },
  { category: 'linux-signals', code: '25', name: 'SIGXFSZ', description: 'File size limit exceeded.' },
  { category: 'linux-signals', code: '26', name: 'SIGVTALRM', description: 'Virtual alarm clock.' },
  { category: 'linux-signals', code: '27', name: 'SIGPROF', description: 'Profiling timer expired.' },
  { category: 'linux-signals', code: '28', name: 'SIGWINCH', description: 'Window resize signal.' },
  { category: 'linux-signals', code: '29', name: 'SIGIO / SIGPOLL', description: 'I/O now possible.' },
  { category: 'linux-signals', code: '30', name: 'SIGPWR', description: 'Power failure.' },
  { category: 'linux-signals', code: '31', name: 'SIGSYS', description: 'Bad system call.' },
  { category: 'linux-signals', code: '134', name: 'Exit code 128+SIGABRT', description: 'Common shell exit code for a process killed by SIGABRT (6): 128 + 6.' },
  { category: 'linux-signals', code: '137', name: 'Exit code 128+SIGKILL', description: 'Common shell exit code for a process killed by SIGKILL (9): 128 + 9 — often an OOM kill.' },
  { category: 'linux-signals', code: '139', name: 'Exit code 128+SIGSEGV', description: 'Common shell exit code for a process killed by SIGSEGV (11): 128 + 11.' },
  { category: 'linux-signals', code: '143', name: 'Exit code 128+SIGTERM', description: 'Common shell exit code for a process killed by SIGTERM (15): 128 + 15.' },

  // SQL (SQLSTATE and vendor-specific codes)
  { category: 'sql', code: '08006', name: 'connection_failure (SQLSTATE)', description: 'Connection failure after being established.' },
  { category: 'sql', code: '22001', name: 'string_data_right_truncation (SQLSTATE)', description: "A value is too long for its column's declared type." },
  { category: 'sql', code: '23505', name: 'unique_violation (PostgreSQL)', description: 'Duplicate key value violates a unique constraint.' },
  { category: 'sql', code: '23503', name: 'foreign_key_violation (PostgreSQL)', description: 'Insert/update violates a foreign key constraint.' },
  { category: 'sql', code: '23502', name: 'not_null_violation (PostgreSQL)', description: 'A NOT NULL column was given a null value.' },
  { category: 'sql', code: '42P01', name: 'undefined_table (PostgreSQL)', description: 'Referenced table does not exist.' },
  { category: 'sql', code: '42703', name: 'undefined_column (PostgreSQL)', description: 'Referenced column does not exist.' },
  { category: 'sql', code: '40001', name: 'serialization_failure (PostgreSQL)', description: 'Could not serialize access due to concurrent update — retry the transaction.' },
  { category: 'sql', code: '1045', name: 'ER_ACCESS_DENIED_ERROR (MySQL)', description: "Access denied for user — bad username/password." },
  { category: 'sql', code: '1046', name: 'ER_NO_DB_ERROR (MySQL)', description: 'No database selected.' },
  { category: 'sql', code: '1054', name: 'ER_BAD_FIELD_ERROR (MySQL)', description: "Unknown column in a field list/where clause." },
  { category: 'sql', code: '1062', name: 'ER_DUP_ENTRY (MySQL)', description: 'Duplicate entry for a unique key.' },
  { category: 'sql', code: '1146', name: 'ER_NO_SUCH_TABLE (MySQL)', description: "Table doesn't exist." },
  { category: 'sql', code: '1213', name: 'ER_LOCK_DEADLOCK (MySQL)', description: 'Deadlock found when trying to get lock — transaction rolled back.' },
  { category: 'sql', code: '2002', name: 'CR_CONNECTION_ERROR (MySQL)', description: "Can't connect to the local MySQL server through the given socket/host." },
  { category: 'sql', code: '208', name: 'Invalid object name (SQL Server)', description: 'Referenced table/view does not exist in the current database.' },
  { category: 'sql', code: '547', name: 'Constraint conflict (SQL Server)', description: 'The statement conflicted with a FOREIGN KEY/CHECK constraint.' },
  { category: 'sql', code: '2627', name: 'Unique key violation (SQL Server)', description: 'Violation of PRIMARY KEY or UNIQUE KEY constraint.' },
  { category: 'sql', code: '18456', name: 'Login failed (SQL Server)', description: 'Login failed for the given user — bad credentials or insufficient permissions.' },
  { category: 'sql', code: '1205', name: 'Deadlock victim (SQL Server)', description: 'Transaction was chosen as the deadlock victim and rolled back.' },

  // TLS alerts (RFC 8446 §6 / IANA TLS Alert Registry)
  { category: 'tls', code: '0', name: 'close_notify', description: 'Notifies the peer that the sender will not send any more messages on this connection.' },
  { category: 'tls', code: '10', name: 'unexpected_message', description: 'An inappropriate message was received.' },
  { category: 'tls', code: '20', name: 'bad_record_mac', description: 'A record was received with an incorrect MAC — often a corrupted or tampered record.' },
  { category: 'tls', code: '22', name: 'record_overflow', description: 'A record was received with a length larger than allowed.' },
  { category: 'tls', code: '40', name: 'handshake_failure', description: 'Unable to negotiate an acceptable set of handshake parameters.' },
  { category: 'tls', code: '42', name: 'bad_certificate', description: "A certificate was corrupt, contained signatures that didn't verify, etc." },
  { category: 'tls', code: '43', name: 'unsupported_certificate', description: 'A certificate was of an unsupported type.' },
  { category: 'tls', code: '44', name: 'certificate_revoked', description: 'A certificate was revoked by its signer.' },
  { category: 'tls', code: '45', name: 'certificate_expired', description: 'A certificate has expired or is not currently valid.' },
  { category: 'tls', code: '46', name: 'certificate_unknown', description: 'Some other (unspecified) issue arose processing the certificate.' },
  { category: 'tls', code: '47', name: 'illegal_parameter', description: 'A field in the handshake was out of range or inconsistent with other fields.' },
  { category: 'tls', code: '48', name: 'unknown_ca', description: 'A valid certificate chain was received, but the CA is not recognized/trusted.' },
  { category: 'tls', code: '49', name: 'access_denied', description: 'A valid certificate was received, but access control refused the operation.' },
  { category: 'tls', code: '50', name: 'decode_error', description: 'A message could not be decoded because a field was out of range or the length was incorrect.' },
  { category: 'tls', code: '51', name: 'decrypt_error', description: 'A handshake cryptographic operation failed (signature verification, key exchange, or validation).' },
  { category: 'tls', code: '70', name: 'protocol_version', description: 'The protocol version the client attempted to negotiate is unsupported.' },
  { category: 'tls', code: '71', name: 'insufficient_security', description: 'The server requires ciphers more secure than those supported by the client.' },
  { category: 'tls', code: '80', name: 'internal_error', description: "An internal error unrelated to the peer or the protocol's correctness makes it impossible to continue." },
  { category: 'tls', code: '90', name: 'user_canceled', description: 'The handshake was canceled for a reason unrelated to a protocol failure.' },
  { category: 'tls', code: '109', name: 'missing_extension', description: 'A handshake message lacked a required extension.' },
  { category: 'tls', code: '110', name: 'unsupported_extension', description: 'An extension was sent that the receiving endpoint did not expect.' },
  { category: 'tls', code: '112', name: 'unrecognized_name', description: 'The server received an SNI hostname it does not recognize.' },
  { category: 'tls', code: '115', name: 'unknown_psk_identity', description: "The client's PSK identity was not recognized by the server." },
  { category: 'tls', code: '116', name: 'certificate_required', description: 'The server requires client authentication but none was provided.' },
  { category: 'tls', code: '120', name: 'no_application_protocol', description: 'ALPN negotiation failed — the server has no supported application protocol.' },

  // DNS response codes (RFC 6895 / IANA DNS RCODEs)
  { category: 'dns', code: '0', name: 'NoError', description: 'No error condition.' },
  { category: 'dns', code: '1', name: 'FormErr', description: 'Format error — the name server was unable to interpret the query.' },
  { category: 'dns', code: '2', name: 'ServFail', description: 'Server failure — the name server encountered an internal problem.' },
  { category: 'dns', code: '3', name: 'NXDomain', description: 'Non-existent domain — the queried name does not exist.' },
  { category: 'dns', code: '4', name: 'NotImp', description: 'Not implemented — the name server does not support the requested query type.' },
  { category: 'dns', code: '5', name: 'Refused', description: 'Query refused, e.g. due to policy reasons.' },
  { category: 'dns', code: '6', name: 'YXDomain', description: 'Name exists when it should not (used in dynamic update).' },
  { category: 'dns', code: '7', name: 'YXRRSet', description: 'RR set exists when it should not (dynamic update).' },
  { category: 'dns', code: '8', name: 'NXRRSet', description: 'RR set that should exist does not (dynamic update).' },
  { category: 'dns', code: '9', name: 'NotAuth', description: 'Server not authoritative for the zone, or not authorized.' },
  { category: 'dns', code: '10', name: 'NotZone', description: 'Name not contained in the zone specified in the Zone Section.' },
  { category: 'dns', code: '16', name: 'BADVERS / BADSIG', description: 'Bad OPT version (EDNS), or TSIG signature failure.' },
  { category: 'dns', code: '17', name: 'BADKEY', description: 'Key not recognized (TSIG/TKEY).' },
  { category: 'dns', code: '18', name: 'BADTIME', description: "Signature out of time window (TSIG)." },
  { category: 'dns', code: '19', name: 'BADMODE', description: 'Bad TKEY mode.' },
  { category: 'dns', code: '20', name: 'BADNAME', description: 'Duplicate key name (TKEY).' },
  { category: 'dns', code: '21', name: 'BADALG', description: 'Algorithm not supported (TKEY).' },
  { category: 'dns', code: '22', name: 'BADTRUNC', description: 'Bad truncation (TSIG).' },
  { category: 'dns', code: '23', name: 'BADCOOKIE', description: 'Bad/missing server cookie (RFC 7873).' },
];
