// Generated by scripts/generate-theme-css.mjs from src/styles/theme/theme-tokens.json - generated, never hand-edit.

export const APPEARANCE_AXES_DATA = {
  "theme": {
    "attr": "data-theme",
    "values": [
      "dark",
      "light"
    ],
    "default": "dark",
    "labels": {
      "dark": "Dark",
      "light": "Light"
    }
  },
  "contrast": {
    "attr": "data-contrast",
    "values": [
      "standard"
    ],
    "default": "standard",
    "labels": {
      "standard": "Standard"
    }
  },
  "accent": {
    "attr": "data-accent",
    "values": [
      "cyan",
      "blue",
      "violet",
      "green",
      "amber",
      "magenta"
    ],
    "default": "cyan",
    "labels": {
      "cyan": "Cyan",
      "blue": "Blue",
      "violet": "Violet",
      "green": "Green",
      "amber": "Amber",
      "magenta": "Magenta"
    }
  },
  "catset": {
    "attr": "data-catset",
    "values": [
      "vivid",
      "soft",
      "cvd"
    ],
    "default": "vivid",
    "labels": {
      "vivid": "Vivid",
      "soft": "Soft",
      "cvd": "Color-blind safe"
    }
  },
  "semantic": {
    "attr": "data-semantic",
    "values": [
      "standard"
    ],
    "default": "standard",
    "labels": {
      "standard": "Standard"
    }
  },
  "density": {
    "attr": "data-density",
    "values": [
      "compact"
    ],
    "default": "compact",
    "labels": {
      "compact": "Compact"
    }
  }
} as const;

export const APPEARANCE_FONTS_DATA = {
  "ui": [
    {
      "id": "system",
      "label": "System UI",
      "stack": "ui-sans-serif, system-ui, -apple-system, 'Segoe UI', sans-serif"
    }
  ],
  "mono": [
    {
      "id": "default",
      "label": "JetBrains Mono / Fira Code",
      "stack": "'JetBrains Mono', 'Fira Code', ui-monospace, 'SFMono-Regular', Menlo, Consolas, monospace"
    }
  ],
  "defaultUi": "system",
  "defaultMono": "default"
} as const;
