import type { ToolMetadata } from "@dude/domain/shared/models/tool-metadata.model";
export const manifest: ToolMetadata = {
    id: 'binary-strings-extractor',
    title: 'Binary Strings Extractor',
    description: 'Extracts printable ASCII and little-endian UTF-16 text runs from an uploaded file, like the Unix `strings` utility, with an adjustable minimum length.',
    category: 'developer',
    keywords: ['strings', 'binary strings', 'ascii', 'utf-16', 'forensics', 'extract text'],
    route: '/tools/binary-strings-extractor',
    status: 'verified',
    verification: {
        propertyTested: true,
        summary: 'Fuzzed extracted report bounds, byte length, and offset ordering over generated byte arrays and options.',
    },
    persistence: { input: 'none', preferences: 'local' },
    execution: { worker: 'optional' },
    io: { accepts: ['file'], produces: ['table'] }
};
