// AUTO-GENERATED by scripts/generate-panel-registry.mjs — do not edit by hand.
// Run `npm run generate:registry` after adding, removing, or editing a <kind-id>.panel-manifest.ts
// file. See ADDING_A_TOOL.md ("Adding a Home panel").

import type { PanelDefinition } from '../../shared/models/panel-definition.model';

export const PANEL_DEFINITIONS: readonly PanelDefinition[] = [
];
