// AUTO-GENERATED by scripts/generate-tool-registry.mjs — do not edit by hand.
// Run `npm run generate:registry` after adding, removing, or editing a <id>.manifest.ts
// file under src/app/tools/. See ADDING_A_TOOL.md.

import type { ToolDefinition } from '../../shared/models/tool-definition.model';
import { manifest as acceptHeaderBuilderManifest } from '../../tools/accept-header-builder/accept-header-builder.manifest';
import { manifest as advancedDiffManifest } from '../../tools/advanced-diff/advanced-diff.manifest';
import { manifest as aesEncryptDecryptManifest } from '../../tools/aes-encrypt-decrypt/aes-encrypt-decrypt.manifest';
import { manifest as archiveToolManifest } from '../../tools/archive-tool/archive-tool.manifest';
import { manifest as asciiArtGeneratorManifest } from '../../tools/ascii-art-generator/ascii-art-generator.manifest';
import { manifest as asciiTableManifest } from '../../tools/ascii-table/ascii-table.manifest';
import { manifest as aspectRatioCalculatorManifest } from '../../tools/aspect-ratio-calculator/aspect-ratio-calculator.manifest';
import { manifest as asymmetricKeyGeneratorManifest } from '../../tools/asymmetric-key-generator/asymmetric-key-generator.manifest';
import { manifest as avroViewerManifest } from '../../tools/avro-viewer/avro-viewer.manifest';
import { manifest as awsSigv4InspectorManifest } from '../../tools/aws-sigv4-inspector/aws-sigv4-inspector.manifest';
import { manifest as barcodeGeneratorManifest } from '../../tools/barcode-generator/barcode-generator.manifest';
import { manifest as barcodeReaderManifest } from '../../tools/barcode-reader/barcode-reader.manifest';
import { manifest as baseNEncoderManifest } from '../../tools/base-n-encoder/base-n-encoder.manifest';
import { manifest as base64ImageViewerManifest } from '../../tools/base64-image-viewer/base64-image-viewer.manifest';
import { manifest as base64Manifest } from '../../tools/base64/base64.manifest';
import { manifest as basicAuthGeneratorManifest } from '../../tools/basic-auth-generator/basic-auth-generator.manifest';
import { manifest as batchOperationsManifest } from '../../tools/batch-operations/batch-operations.manifest';
import { manifest as batchRenameManifest } from '../../tools/batch-rename/batch-rename.manifest';
import { manifest as batchTextConverterManifest } from '../../tools/batch-text-converter/batch-text-converter.manifest';
import { manifest as bearerTokenBuilderManifest } from '../../tools/bearer-token-builder/bearer-token-builder.manifest';
import { manifest as bigintCalculatorManifest } from '../../tools/bigint-calculator/bigint-calculator.manifest';
import { manifest as binaryStringsExtractorManifest } from '../../tools/binary-strings-extractor/binary-strings-extractor.manifest';
import { manifest as binaryStructureInspectorManifest } from '../../tools/binary-structure-inspector/binary-structure-inspector.manifest';
import { manifest as bomDetectorManifest } from '../../tools/bom-detector/bom-detector.manifest';
import { manifest as borderRadiusGeneratorManifest } from '../../tools/border-radius-generator/border-radius-generator.manifest';
import { manifest as boxShadowGeneratorManifest } from '../../tools/box-shadow-generator/box-shadow-generator.manifest';
import { manifest as branchNameGeneratorManifest } from '../../tools/branch-name-generator/branch-name-generator.manifest';
import { manifest as bsonViewerManifest } from '../../tools/bson-viewer/bson-viewer.manifest';
import { manifest as byteFrequencyAnalyzerManifest } from '../../tools/byte-frequency-analyzer/byte-frequency-analyzer.manifest';
import { manifest as cacheControlBuilderManifest } from '../../tools/cache-control-builder/cache-control-builder.manifest';
import { manifest as caseConverterManifest } from '../../tools/case-converter/case-converter.manifest';
import { manifest as cborViewerManifest } from '../../tools/cbor-viewer/cbor-viewer.manifest';
import { manifest as certificateChainToolsManifest } from '../../tools/certificate-chain-tools/certificate-chain-tools.manifest';
import { manifest as certificateWatchListManifest } from '../../tools/certificate-watch-list/certificate-watch-list.manifest';
import { manifest as chacha20Poly1305Manifest } from '../../tools/chacha20-poly1305/chacha20-poly1305.manifest';
import { manifest as chmodConverterManifest } from '../../tools/chmod-converter/chmod-converter.manifest';
import { manifest as cidrCalculatorManifest } from '../../tools/cidr-calculator/cidr-calculator.manifest';
import { manifest as colorBlindnessSimulatorManifest } from '../../tools/color-blindness-simulator/color-blindness-simulator.manifest';
import { manifest as colorConverterManifest } from '../../tools/color-converter/color-converter.manifest';
import { manifest as commitMessageValidatorManifest } from '../../tools/commit-message-validator/commit-message-validator.manifest';
import { manifest as compressionLabManifest } from '../../tools/compression-lab/compression-lab.manifest';
import { manifest as configFileComparatorManifest } from '../../tools/config-file-comparator/config-file-comparator.manifest';
import { manifest as configMergeToolManifest } from '../../tools/config-merge-tool/config-merge-tool.manifest';
import { manifest as connectivityTesterManifest } from '../../tools/connectivity-tester/connectivity-tester.manifest';
import { manifest as contentDispositionBuilderManifest } from '../../tools/content-disposition-builder/content-disposition-builder.manifest';
import { manifest as contrastCheckerManifest } from '../../tools/contrast-checker/contrast-checker.manifest';
import { manifest as conventionalCommitBuilderManifest } from '../../tools/conventional-commit-builder/conventional-commit-builder.manifest';
import { manifest as cookieToolsManifest } from '../../tools/cookie-tools/cookie-tools.manifest';
import { manifest as corsHeaderBuilderManifest } from '../../tools/cors-header-builder/cors-header-builder.manifest';
import { manifest as createTableGeneratorManifest } from '../../tools/create-table-generator/create-table-generator.manifest';
import { manifest as cronManifest } from '../../tools/cron/cron.manifest';
import { manifest as cspBuilderManifest } from '../../tools/csp-builder/csp-builder.manifest';
import { manifest as csrGeneratorInspectorManifest } from '../../tools/csr-generator-inspector/csr-generator-inspector.manifest';
import { manifest as cssAnimationBuilderManifest } from '../../tools/css-animation-builder/css-animation-builder.manifest';
import { manifest as cssFormatterManifest } from '../../tools/css-formatter/css-formatter.manifest';
import { manifest as cssGridPlaygroundManifest } from '../../tools/css-grid-playground/css-grid-playground.manifest';
import { manifest as cssSelectorTesterManifest } from '../../tools/css-selector-tester/css-selector-tester.manifest';
import { manifest as cssSpecificityCalculatorManifest } from '../../tools/css-specificity-calculator/css-specificity-calculator.manifest';
import { manifest as cssTransformBuilderManifest } from '../../tools/css-transform-builder/css-transform-builder.manifest';
import { manifest as csvCleanerManifest } from '../../tools/csv-cleaner/csv-cleaner.manifest';
import { manifest as csvDedupeManifest } from '../../tools/csv-dedupe/csv-dedupe.manifest';
import { manifest as csvDelimiterDetectorManifest } from '../../tools/csv-delimiter-detector/csv-delimiter-detector.manifest';
import { manifest as csvFilterSortManifest } from '../../tools/csv-filter-sort/csv-filter-sort.manifest';
import { manifest as csvJoinManifest } from '../../tools/csv-join/csv-join.manifest';
import { manifest as csvPivotManifest } from '../../tools/csv-pivot/csv-pivot.manifest';
import { manifest as csvSqlManifest } from '../../tools/csv-sql/csv-sql.manifest';
import { manifest as csvStatsManifest } from '../../tools/csv-stats/csv-stats.manifest';
import { manifest as csvViewerManifest } from '../../tools/csv-viewer/csv-viewer.manifest';
import { manifest as ctLookupManifest } from '../../tools/ct-lookup/ct-lookup.manifest';
import { manifest as cubicBezierEditorManifest } from '../../tools/cubic-bezier-editor/cubic-bezier-editor.manifest';
import { manifest as cuidGeneratorManifest } from '../../tools/cuid-generator/cuid-generator.manifest';
import { manifest as curlConverterManifest } from '../../tools/curl-converter/curl-converter.manifest';
import { manifest as dataUriConverterManifest } from '../../tools/data-uri-converter/data-uri-converter.manifest';
import { manifest as dateCalculatorManifest } from '../../tools/date-calculator/date-calculator.manifest';
import { manifest as dependencyVersionComparatorManifest } from '../../tools/dependency-version-comparator/dependency-version-comparator.manifest';
import { manifest as devSnippetsReferenceManifest } from '../../tools/dev-snippets-reference/dev-snippets-reference.manifest';
import { manifest as diffManifest } from '../../tools/diff/diff.manifest';
import { manifest as directoryDiffManifest } from '../../tools/directory-diff/directory-diff.manifest';
import { manifest as directoryTreeGeneratorManifest } from '../../tools/directory-tree-generator/directory-tree-generator.manifest';
import { manifest as dnsLookupManifest } from '../../tools/dns-lookup/dns-lookup.manifest';
import { manifest as dnsPropagationManifest } from '../../tools/dns-propagation/dns-propagation.manifest';
import { manifest as dnssecInspectorManifest } from '../../tools/dnssec-inspector/dnssec-inspector.manifest';
import { manifest as dockerComposeValidatorManifest } from '../../tools/docker-compose-validator/docker-compose-validator.manifest';
import { manifest as dockerRunComposeConverterManifest } from '../../tools/docker-run-compose-converter/docker-run-compose-converter.manifest';
import { manifest as dockerfileLinterManifest } from '../../tools/dockerfile-linter/dockerfile-linter.manifest';
import { manifest as domTreeViewerManifest } from '../../tools/dom-tree-viewer/dom-tree-viewer.manifest';
import { manifest as dpiCalculatorManifest } from '../../tools/dpi-calculator/dpi-calculator.manifest';
import { manifest as dstTransitionExplorerManifest } from '../../tools/dst-transition-explorer/dst-transition-explorer.manifest';
import { manifest as duplicateFilesManifest } from '../../tools/duplicate-files/duplicate-files.manifest';
import { manifest as duplicateFinderManifest } from '../../tools/duplicate-finder/duplicate-finder.manifest';
import { manifest as durationFormatterManifest } from '../../tools/duration-formatter/duration-formatter.manifest';
import { manifest as elfHeaderViewerManifest } from '../../tools/elf-header-viewer/elf-header-viewer.manifest';
import { manifest as emailAuthInspectorManifest } from '../../tools/email-auth-inspector/email-auth-inspector.manifest';
import { manifest as encodingDetectorManifest } from '../../tools/encoding-detector/encoding-detector.manifest';
import { manifest as envDiffManifest } from '../../tools/env-diff/env-diff.manifest';
import { manifest as envEditorManifest } from '../../tools/env-editor/env-editor.manifest';
import { manifest as envJsonConverterManifest } from '../../tools/env-json-converter/env-json-converter.manifest';
import { manifest as envValidatorManifest } from '../../tools/env-validator/env-validator.manifest';
import { manifest as environmentVariablesManifest } from '../../tools/environment-variables/environment-variables.manifest';
import { manifest as epochTimelineVisualizerManifest } from '../../tools/epoch-timeline-visualizer/epoch-timeline-visualizer.manifest';
import { manifest as errorCodeReferenceManifest } from '../../tools/error-code-reference/error-code-reference.manifest';
import { manifest as escapeUnescapeToolkitManifest } from '../../tools/escape-unescape-toolkit/escape-unescape-toolkit.manifest';
import { manifest as eventLogViewerManifest } from '../../tools/event-log-viewer/event-log-viewer.manifest';
import { manifest as exifViewerManifest } from '../../tools/exif-viewer/exif-viewer.manifest';
import { manifest as expressionEvaluatorManifest } from '../../tools/expression-evaluator/expression-evaluator.manifest';
import { manifest as extractColumnsManifest } from '../../tools/extract-columns/extract-columns.manifest';
import { manifest as fileBase64Manifest } from '../../tools/file-base64/file-base64.manifest';
import { manifest as fileEntropyAnalyzerManifest } from '../../tools/file-entropy-analyzer/file-entropy-analyzer.manifest';
import { manifest as fileHashManifest } from '../../tools/file-hash/file-hash.manifest';
import { manifest as fileInspectorManifest } from '../../tools/file-inspector/file-inspector.manifest';
import { manifest as fileSplitJoinManifest } from '../../tools/file-split-join/file-split-join.manifest';
import { manifest as fileTypeDetectorManifest } from '../../tools/file-type-detector/file-type-detector.manifest';
import { manifest as findReplaceTextManifest } from '../../tools/find-replace-text/find-replace-text.manifest';
import { manifest as flexboxPlaygroundManifest } from '../../tools/flexbox-playground/flexbox-playground.manifest';
import { manifest as folderSizeAnalyzerManifest } from '../../tools/folder-size-analyzer/folder-size-analyzer.manifest';
import { manifest as gitCommandBuilderManifest } from '../../tools/git-command-builder/git-command-builder.manifest';
import { manifest as gitCommandExplainerManifest } from '../../tools/git-command-explainer/git-command-explainer.manifest';
import { manifest as gitDiffManifest } from '../../tools/git-diff/git-diff.manifest';
import { manifest as gitRemoteInspectorManifest } from '../../tools/git-remote-inspector/git-remote-inspector.manifest';
import { manifest as gitUrlParserManifest } from '../../tools/git-url-parser/git-url-parser.manifest';
import { manifest as gitignoreGeneratorManifest } from '../../tools/gitignore-generator/gitignore-generator.manifest';
import { manifest as gitignoreTesterManifest } from '../../tools/gitignore-tester/gitignore-tester.manifest';
import { manifest as globTesterManifest } from '../../tools/glob-tester/glob-tester.manifest';
import { manifest as gradientGeneratorManifest } from '../../tools/gradient-generator/gradient-generator.manifest';
import { manifest as hashManifestManifest } from '../../tools/hash-manifest/hash-manifest.manifest';
import { manifest as hashManifest } from '../../tools/hash/hash.manifest';
import { manifest as hexDiffManifest } from '../../tools/hex-diff/hex-diff.manifest';
import { manifest as hexDumpManifest } from '../../tools/hex-dump/hex-dump.manifest';
import { manifest as hexEditorManifest } from '../../tools/hex-editor/hex-editor.manifest';
import { manifest as hexTextConverterManifest } from '../../tools/hex-text-converter/hex-text-converter.manifest';
import { manifest as hmacGeneratorManifest } from '../../tools/hmac-generator/hmac-generator.manifest';
import { manifest as hostnameResolverManifest } from '../../tools/hostname-resolver/hostname-resolver.manifest';
import { manifest as htmlEntitiesManifest } from '../../tools/html-entities/html-entities.manifest';
import { manifest as htmlEntityExplorerManifest } from '../../tools/html-entity-explorer/html-entity-explorer.manifest';
import { manifest as htmlFormatterManifest } from '../../tools/html-formatter/html-formatter.manifest';
import { manifest as htmlJsxConverterManifest } from '../../tools/html-jsx-converter/html-jsx-converter.manifest';
import { manifest as htmlPreviewManifest } from '../../tools/html-preview/html-preview.manifest';
import { manifest as httpDigestAuthHelperManifest } from '../../tools/http-digest-auth-helper/http-digest-auth-helper.manifest';
import { manifest as httpHeaderInspectorManifest } from '../../tools/http-header-inspector/http-header-inspector.manifest';
import { manifest as httpRequestBuilderManifest } from '../../tools/http-request-builder/http-request-builder.manifest';
import { manifest as httpResponseViewerManifest } from '../../tools/http-response-viewer/http-response-viewer.manifest';
import { manifest as httpStatusManifest } from '../../tools/http-status/http-status.manifest';
import { manifest as httpsConfigAnalyzerManifest } from '../../tools/https-config-analyzer/https-config-analyzer.manifest';
import { manifest as imageCompressorManifest } from '../../tools/image-compressor/image-compressor.manifest';
import { manifest as imageCropperManifest } from '../../tools/image-cropper/image-cropper.manifest';
import { manifest as imageFormatConverterManifest } from '../../tools/image-format-converter/image-format-converter.manifest';
import { manifest as imageMetadataInspectorManifest } from '../../tools/image-metadata-inspector/image-metadata-inspector.manifest';
import { manifest as imageResizerManifest } from '../../tools/image-resizer/image-resizer.manifest';
import { manifest as iniFormatterManifest } from '../../tools/ini-formatter/ini-formatter.manifest';
import { manifest as installedSoftwareManifest } from '../../tools/installed-software/installed-software.manifest';
import { manifest as invisibleCharScannerManifest } from '../../tools/invisible-char-scanner/invisible-char-scanner.manifest';
import { manifest as ipAddressInspectorManifest } from '../../tools/ip-address-inspector/ip-address-inspector.manifest';
import { manifest as ipv4IntegerConverterManifest } from '../../tools/ipv4-integer-converter/ipv4-integer-converter.manifest';
import { manifest as ipv6ExplorerManifest } from '../../tools/ipv6-explorer/ipv6-explorer.manifest';
import { manifest as jsPlaygroundManifest } from '../../tools/js-playground/js-playground.manifest';
import { manifest as jsonFlattenManifest } from '../../tools/json-flatten/json-flatten.manifest';
import { manifest as jsonLdTesterManifest } from '../../tools/json-ld-tester/json-ld-tester.manifest';
import { manifest as jsonMergeManifest } from '../../tools/json-merge/json-merge.manifest';
import { manifest as jsonPatchGenerateManifest } from '../../tools/json-patch-generate/json-patch-generate.manifest';
import { manifest as jsonPatchTestManifest } from '../../tools/json-patch-test/json-patch-test.manifest';
import { manifest as jsonPointerManifest } from '../../tools/json-pointer/json-pointer.manifest';
import { manifest as jsonQueryManifest } from '../../tools/json-query/json-query.manifest';
import { manifest as jsonSchemaValidatorManifest } from '../../tools/json-schema-validator/json-schema-validator.manifest';
import { manifest as jsonSortKeysManifest } from '../../tools/json-sort-keys/json-sort-keys.manifest';
import { manifest as jsonManifest } from '../../tools/json/json.manifest';
import { manifest as jsonlViewerManifest } from '../../tools/jsonl-viewer/jsonl-viewer.manifest';
import { manifest as jwksToPemManifest } from '../../tools/jwks-to-pem/jwks-to-pem.manifest';
import { manifest as jwksViewerManifest } from '../../tools/jwks-viewer/jwks-viewer.manifest';
import { manifest as jwtClaimsAnalyzerManifest } from '../../tools/jwt-claims-analyzer/jwt-claims-analyzer.manifest';
import { manifest as jwtExpirationVisualizerManifest } from '../../tools/jwt-expiration-visualizer/jwt-expiration-visualizer.manifest';
import { manifest as jwtSignerManifest } from '../../tools/jwt-signer/jwt-signer.manifest';
import { manifest as jwtVerifyManifest } from '../../tools/jwt-verify/jwt-verify.manifest';
import { manifest as jwtManifest } from '../../tools/jwt/jwt.manifest';
import { manifest as k8sCronjobTesterManifest } from '../../tools/k8s-cronjob-tester/k8s-cronjob-tester.manifest';
import { manifest as k8sManifestDiffManifest } from '../../tools/k8s-manifest-diff/k8s-manifest-diff.manifest';
import { manifest as k8sManifestValidatorManifest } from '../../tools/k8s-manifest-validator/k8s-manifest-validator.manifest';
import { manifest as k8sQuantityConverterManifest } from '../../tools/k8s-quantity-converter/k8s-quantity-converter.manifest';
import { manifest as k8sResourceCalculatorManifest } from '../../tools/k8s-resource-calculator/k8s-resource-calculator.manifest';
import { manifest as k8sSecretBase64Manifest } from '../../tools/k8s-secret-base64/k8s-secret-base64.manifest';
import { manifest as keywordFrequencyAnalyzerManifest } from '../../tools/keyword-frequency-analyzer/keyword-frequency-analyzer.manifest';
import { manifest as ksuidToolsManifest } from '../../tools/ksuid-tools/ksuid-tools.manifest';
import { manifest as kubeconfigInspectorManifest } from '../../tools/kubeconfig-inspector/kubeconfig-inspector.manifest';
import { manifest as largeFileInspectorManifest } from '../../tools/large-file-inspector/large-file-inspector.manifest';
import { manifest as latencyMonitorManifest } from '../../tools/latency-monitor/latency-monitor.manifest';
import { manifest as lineOrderToolsManifest } from '../../tools/line-order-tools/line-order-tools.manifest';
import { manifest as linePrefixNumberingManifest } from '../../tools/line-prefix-numbering/line-prefix-numbering.manifest';
import { manifest as liveCertificateChainManifest } from '../../tools/live-certificate-chain/live-certificate-chain.manifest';
import { manifest as localNetworkManifest } from '../../tools/local-network/local-network.manifest';
import { manifest as lockfileInspectorManifest } from '../../tools/lockfile-inspector/lockfile-inspector.manifest';
import { manifest as loremIpsumGeneratorManifest } from '../../tools/lorem-ipsum-generator/lorem-ipsum-generator.manifest';
import { manifest as macAddressInspectorManifest } from '../../tools/mac-address-inspector/mac-address-inspector.manifest';
import { manifest as machoHeaderViewerManifest } from '../../tools/macho-header-viewer/macho-header-viewer.manifest';
import { manifest as markdownWorkspaceManifest } from '../../tools/markdown-workspace/markdown-workspace.manifest';
import { manifest as markdownManifest } from '../../tools/markdown/markdown.manifest';
import { manifest as matrixCalculatorManifest } from '../../tools/matrix-calculator/matrix-calculator.manifest';
import { manifest as metaTagGeneratorManifest } from '../../tools/meta-tag-generator/meta-tag-generator.manifest';
import { manifest as mimeTypesManifest } from '../../tools/mime-types/mime-types.manifest';
import { manifest as missingEnvVarDetectorManifest } from '../../tools/missing-env-var-detector/missing-env-var-detector.manifest';
import { manifest as mockDataStudioManifest } from '../../tools/mock-data-studio/mock-data-studio.manifest';
import { manifest as modelGeneratorManifest } from '../../tools/model-generator/model-generator.manifest';
import { manifest as msgpackDecoderManifest } from '../../tools/msgpack-decoder/msgpack-decoder.manifest';
import { manifest as mtuDiscoveryManifest } from '../../tools/mtu-discovery/mtu-discovery.manifest';
import { manifest as multipartFormBuilderManifest } from '../../tools/multipart-form-builder/multipart-form-builder.manifest';
import { manifest as nanoidGeneratorManifest } from '../../tools/nanoid-generator/nanoid-generator.manifest';
import { manifest as networkDiagnosticBundleManifest } from '../../tools/network-diagnostic-bundle/network-diagnostic-bundle.manifest';
import { manifest as numberBaseManifest } from '../../tools/number-base/number-base.manifest';
import { manifest as numberTheoryToolkitManifest } from '../../tools/number-theory-toolkit/number-theory-toolkit.manifest';
import { manifest as numericRepresentationInspectorManifest } from '../../tools/numeric-representation-inspector/numeric-representation-inspector.manifest';
import { manifest as oauthPlaygroundManifest } from '../../tools/oauth-playground/oauth-playground.manifest';
import { manifest as oauthScopeParserManifest } from '../../tools/oauth-scope-parser/oauth-scope-parser.manifest';
import { manifest as oauthTokenInspectorManifest } from '../../tools/oauth-token-inspector/oauth-token-inspector.manifest';
import { manifest as oidcDiscoveryInspectorManifest } from '../../tools/oidc-discovery-inspector/oidc-discovery-inspector.manifest';
import { manifest as opengraphPreviewManifest } from '../../tools/opengraph-preview/opengraph-preview.manifest';
import { manifest as packageMetadataInspectorManifest } from '../../tools/package-metadata-inspector/package-metadata-inspector.manifest';
import { manifest as packetLossManifest } from '../../tools/packet-loss/packet-loss.manifest';
import { manifest as paletteGeneratorManifest } from '../../tools/palette-generator/palette-generator.manifest';
import { manifest as parquetViewerManifest } from '../../tools/parquet-viewer/parquet-viewer.manifest';
import { manifest as passwordGeneratorManifest } from '../../tools/password-generator/password-generator.manifest';
import { manifest as passwordStrengthAnalyzerManifest } from '../../tools/password-strength-analyzer/password-strength-analyzer.manifest';
import { manifest as pathEditorManifest } from '../../tools/path-editor/path-editor.manifest';
import { manifest as peHeaderViewerManifest } from '../../tools/pe-header-viewer/pe-header-viewer.manifest';
import { manifest as pemDerInspectorManifest } from '../../tools/pem-der-inspector/pem-der-inspector.manifest';
import { manifest as percentageRatioCalculatorManifest } from '../../tools/percentage-ratio-calculator/percentage-ratio-calculator.manifest';
import { manifest as pingManifest } from '../../tools/ping/ping.manifest';
import { manifest as pixelColorPickerManifest } from '../../tools/pixel-color-picker/pixel-color-picker.manifest';
import { manifest as pkceGeneratorManifest } from '../../tools/pkce-generator/pkce-generator.manifest';
import { manifest as pkceVerifierManifest } from '../../tools/pkce-verifier/pkce-verifier.manifest';
import { manifest as pkcs12InspectorManifest } from '../../tools/pkcs12-inspector/pkcs12-inspector.manifest';
import { manifest as portProcessLookupManifest } from '../../tools/port-process-lookup/port-process-lookup.manifest';
import { manifest as portScannerManifest } from '../../tools/port-scanner/port-scanner.manifest';
import { manifest as processViewerManifest } from '../../tools/process-viewer/process-viewer.manifest';
import { manifest as programmerCalculatorManifest } from '../../tools/programmer-calculator/programmer-calculator.manifest';
import { manifest as propertiesParserManifest } from '../../tools/properties-parser/properties-parser.manifest';
import { manifest as protobufDecoderManifest } from '../../tools/protobuf-decoder/protobuf-decoder.manifest';
import { manifest as publicIpManifest } from '../../tools/public-ip/public-ip.manifest';
import { manifest as punycodeConverterManifest } from '../../tools/punycode-converter/punycode-converter.manifest';
import { manifest as pythonPlaygroundManifest } from '../../tools/python-playground/python-playground.manifest';
import { manifest as qrCodeGeneratorManifest } from '../../tools/qr-code-generator/qr-code-generator.manifest';
import { manifest as qrCodeScannerManifest } from '../../tools/qr-code-scanner/qr-code-scanner.manifest';
import { manifest as queryStringManifest } from '../../tools/query-string/query-string.manifest';
import { manifest as randomDataGeneratorManifest } from '../../tools/random-data-generator/random-data-generator.manifest';
import { manifest as rangeGeneratorManifest } from '../../tools/range-generator/range-generator.manifest';
import { manifest as rangeHeaderBuilderManifest } from '../../tools/range-header-builder/range-header-builder.manifest';
import { manifest as recurrenceRuleManifest } from '../../tools/recurrence-rule/recurrence-rule.manifest';
import { manifest as regexBenchmarkManifest } from '../../tools/regex-benchmark/regex-benchmark.manifest';
import { manifest as regexFlavorConverterManifest } from '../../tools/regex-flavor-converter/regex-flavor-converter.manifest';
import { manifest as regexGeneratorManifest } from '../../tools/regex-generator/regex-generator.manifest';
import { manifest as regexVisualizerManifest } from '../../tools/regex-visualizer/regex-visualizer.manifest';
import { manifest as regexManifest } from '../../tools/regex/regex.manifest';
import { manifest as registryEditorManifest } from '../../tools/registry-editor/registry-editor.manifest';
import { manifest as relativeTimeParserManifest } from '../../tools/relative-time-parser/relative-time-parser.manifest';
import { manifest as resolutionCalculatorManifest } from '../../tools/resolution-calculator/resolution-calculator.manifest';
import { manifest as resxToolManifest } from '../../tools/resx-tool/resx-tool.manifest';
import { manifest as reverseDnsManifest } from '../../tools/reverse-dns/reverse-dns.manifest';
import { manifest as revocationInspectorManifest } from '../../tools/revocation-inspector/revocation-inspector.manifest';
import { manifest as richTextEditorManifest } from '../../tools/rich-text-editor/rich-text-editor.manifest';
import { manifest as rotCipherManifest } from '../../tools/rot-cipher/rot-cipher.manifest';
import { manifest as routeComparisonManifest } from '../../tools/route-comparison/route-comparison.manifest';
import { manifest as runtimeDetectorManifest } from '../../tools/runtime-detector/runtime-detector.manifest';
import { manifest as scheduledTasksManifest } from '../../tools/scheduled-tasks/scheduled-tasks.manifest';
import { manifest as schemaDiffManifest } from '../../tools/schema-diff/schema-diff.manifest';
import { manifest as scientificNotationConverterManifest } from '../../tools/scientific-notation-converter/scientific-notation-converter.manifest';
import { manifest as secretDetectorManifest } from '../../tools/secret-detector/secret-detector.manifest';
import { manifest as semverComparatorManifest } from '../../tools/semver-comparator/semver-comparator.manifest';
import { manifest as servicesViewerManifest } from '../../tools/services-viewer/services-viewer.manifest';
import { manifest as slugGeneratorManifest } from '../../tools/slug-generator/slug-generator.manifest';
import { manifest as smartQuotesNormalizerManifest } from '../../tools/smart-quotes-normalizer/smart-quotes-normalizer.manifest';
import { manifest as snowflakeIdToolsManifest } from '../../tools/snowflake-id-tools/snowflake-id-tools.manifest';
import { manifest as soundexMetaphoneManifest } from '../../tools/soundex-metaphone/soundex-metaphone.manifest';
import { manifest as sqlDialectConverterManifest } from '../../tools/sql-dialect-converter/sql-dialect-converter.manifest';
import { manifest as sqlFormatterToolManifest } from '../../tools/sql-formatter-tool/sql-formatter-tool.manifest';
import { manifest as sqlParameterizerManifest } from '../../tools/sql-parameterizer/sql-parameterizer.manifest';
import { manifest as sqlQueryExplainerManifest } from '../../tools/sql-query-explainer/sql-query-explainer.manifest';
import { manifest as sqlSyntaxCheckerManifest } from '../../tools/sql-syntax-checker/sql-syntax-checker.manifest';
import { manifest as sqliteViewerManifest } from '../../tools/sqlite-viewer/sqlite-viewer.manifest';
import { manifest as sshKeyToolsManifest } from '../../tools/ssh-key-tools/ssh-key-tools.manifest';
import { manifest as stackTraceFormatterManifest } from '../../tools/stack-trace-formatter/stack-trace-formatter.manifest';
import { manifest as starttlsInspectorManifest } from '../../tools/starttls-inspector/starttls-inspector.manifest';
import { manifest as startupProgramsManifest } from '../../tools/startup-programs/startup-programs.manifest';
import { manifest as statisticsCalculatorManifest } from '../../tools/statistics-calculator/statistics-calculator.manifest';
import { manifest as stopwatchCountdownManifest } from '../../tools/stopwatch-countdown/stopwatch-countdown.manifest';
import { manifest as stringSimilarityCalculatorManifest } from '../../tools/string-similarity-calculator/string-similarity-calculator.manifest';
import { manifest as structuredDataConverterManifest } from '../../tools/structured-data-converter/structured-data-converter.manifest';
import { manifest as subnetCalculatorManifest } from '../../tools/subnet-calculator/subnet-calculator.manifest';
import { manifest as svgDataUriManifest } from '../../tools/svg-data-uri/svg-data-uri.manifest';
import { manifest as svgViewerManifest } from '../../tools/svg-viewer/svg-viewer.manifest';
import { manifest as systemChangesManifest } from '../../tools/system-changes/system-changes.manifest';
import { manifest as tailwindColorMatcherManifest } from '../../tools/tailwind-color-matcher/tailwind-color-matcher.manifest';
import { manifest as tcpPortTesterManifest } from '../../tools/tcp-port-tester/tcp-port-tester.manifest';
import { manifest as templateRendererManifest } from '../../tools/template-renderer/template-renderer.manifest';
import { manifest as textInspectorManifest } from '../../tools/text-inspector/text-inspector.manifest';
import { manifest as textTokenizerNgramManifest } from '../../tools/text-tokenizer-ngram/text-tokenizer-ngram.manifest';
import { manifest as timezoneConverterManifest } from '../../tools/timezone-converter/timezone-converter.manifest';
import { manifest as timezoneOffsetComparatorManifest } from '../../tools/timezone-offset-comparator/timezone-offset-comparator.manifest';
import { manifest as tlsInspectorManifest } from '../../tools/tls-inspector/tls-inspector.manifest';
import { manifest as tomlFormatterManifest } from '../../tools/toml-formatter/toml-formatter.manifest';
import { manifest as tracerouteManifest } from '../../tools/traceroute/traceroute.manifest';
import { manifest as treeSearchManifest } from '../../tools/tree-search/tree-search.manifest';
import { manifest as udpPortTesterManifest } from '../../tools/udp-port-tester/udp-port-tester.manifest';
import { manifest as ulidToolsManifest } from '../../tools/ulid-tools/ulid-tools.manifest';
import { manifest as unicodeCharacterInspectorManifest } from '../../tools/unicode-character-inspector/unicode-character-inspector.manifest';
import { manifest as unicodeCodePointConverterManifest } from '../../tools/unicode-code-point-converter/unicode-code-point-converter.manifest';
import { manifest as unicodeNormalizationManifest } from '../../tools/unicode-normalization/unicode-normalization.manifest';
import { manifest as unicodeTableManifest } from '../../tools/unicode-table/unicode-table.manifest';
import { manifest as unixTimestampManifest } from '../../tools/unix-timestamp/unix-timestamp.manifest';
import { manifest as urlEncodeManifest } from '../../tools/url-encode/url-encode.manifest';
import { manifest as urlInspectorManifest } from '../../tools/url-inspector/url-inspector.manifest';
import { manifest as urlNormalizerManifest } from '../../tools/url-normalizer/url-normalizer.manifest';
import { manifest as urlPercentInspectorManifest } from '../../tools/url-percent-inspector/url-percent-inspector.manifest';
import { manifest as urlSafetyInspectorManifest } from '../../tools/url-safety-inspector/url-safety-inspector.manifest';
import { manifest as userAgentManifest } from '../../tools/user-agent/user-agent.manifest';
import { manifest as uuidManifest } from '../../tools/uuid/uuid.manifest';
import { manifest as watchedFoldersManifest } from '../../tools/watched-folders/watched-folders.manifest';
import { manifest as weekNumberCalculatorManifest } from '../../tools/week-number-calculator/week-number-calculator.manifest';
import { manifest as whitespaceCleanerManifest } from '../../tools/whitespace-cleaner/whitespace-cleaner.manifest';
import { manifest as whoisLookupManifest } from '../../tools/whois-lookup/whois-lookup.manifest';
import { manifest as windowsFeaturesManifest } from '../../tools/windows-features/windows-features.manifest';
import { manifest as x509CertificateInspectorManifest } from '../../tools/x509-certificate-inspector/x509-certificate-inspector.manifest';
import { manifest as xmlCsvManifest } from '../../tools/xml-csv/xml-csv.manifest';
import { manifest as xmlFormatterManifest } from '../../tools/xml-formatter/xml-formatter.manifest';
import { manifest as xmlXpathManifest } from '../../tools/xml-xpath/xml-xpath.manifest';
import { manifest as xmlXsdValidatorManifest } from '../../tools/xml-xsd-validator/xml-xsd-validator.manifest';
import { manifest as yamlAnchorsManifest } from '../../tools/yaml-anchors/yaml-anchors.manifest';
import { manifest as yamlJsonManifest } from '../../tools/yaml-json/yaml-json.manifest';
import { manifest as yamlLinterManifest } from '../../tools/yaml-linter/yaml-linter.manifest';
import { manifest as yamlMergeManifest } from '../../tools/yaml-merge/yaml-merge.manifest';
import { manifest as yamlPathManifest } from '../../tools/yaml-path/yaml-path.manifest';

export const TOOL_DEFINITIONS: readonly ToolDefinition[] = [
  acceptHeaderBuilderManifest,
  advancedDiffManifest,
  aesEncryptDecryptManifest,
  archiveToolManifest,
  asciiArtGeneratorManifest,
  asciiTableManifest,
  aspectRatioCalculatorManifest,
  asymmetricKeyGeneratorManifest,
  avroViewerManifest,
  awsSigv4InspectorManifest,
  barcodeGeneratorManifest,
  barcodeReaderManifest,
  baseNEncoderManifest,
  base64ImageViewerManifest,
  base64Manifest,
  basicAuthGeneratorManifest,
  batchOperationsManifest,
  batchRenameManifest,
  batchTextConverterManifest,
  bearerTokenBuilderManifest,
  bigintCalculatorManifest,
  binaryStringsExtractorManifest,
  binaryStructureInspectorManifest,
  bomDetectorManifest,
  borderRadiusGeneratorManifest,
  boxShadowGeneratorManifest,
  branchNameGeneratorManifest,
  bsonViewerManifest,
  byteFrequencyAnalyzerManifest,
  cacheControlBuilderManifest,
  caseConverterManifest,
  cborViewerManifest,
  certificateChainToolsManifest,
  certificateWatchListManifest,
  chacha20Poly1305Manifest,
  chmodConverterManifest,
  cidrCalculatorManifest,
  colorBlindnessSimulatorManifest,
  colorConverterManifest,
  commitMessageValidatorManifest,
  compressionLabManifest,
  configFileComparatorManifest,
  configMergeToolManifest,
  connectivityTesterManifest,
  contentDispositionBuilderManifest,
  contrastCheckerManifest,
  conventionalCommitBuilderManifest,
  cookieToolsManifest,
  corsHeaderBuilderManifest,
  createTableGeneratorManifest,
  cronManifest,
  cspBuilderManifest,
  csrGeneratorInspectorManifest,
  cssAnimationBuilderManifest,
  cssFormatterManifest,
  cssGridPlaygroundManifest,
  cssSelectorTesterManifest,
  cssSpecificityCalculatorManifest,
  cssTransformBuilderManifest,
  csvCleanerManifest,
  csvDedupeManifest,
  csvDelimiterDetectorManifest,
  csvFilterSortManifest,
  csvJoinManifest,
  csvPivotManifest,
  csvSqlManifest,
  csvStatsManifest,
  csvViewerManifest,
  ctLookupManifest,
  cubicBezierEditorManifest,
  cuidGeneratorManifest,
  curlConverterManifest,
  dataUriConverterManifest,
  dateCalculatorManifest,
  dependencyVersionComparatorManifest,
  devSnippetsReferenceManifest,
  diffManifest,
  directoryDiffManifest,
  directoryTreeGeneratorManifest,
  dnsLookupManifest,
  dnsPropagationManifest,
  dnssecInspectorManifest,
  dockerComposeValidatorManifest,
  dockerRunComposeConverterManifest,
  dockerfileLinterManifest,
  domTreeViewerManifest,
  dpiCalculatorManifest,
  dstTransitionExplorerManifest,
  duplicateFilesManifest,
  duplicateFinderManifest,
  durationFormatterManifest,
  elfHeaderViewerManifest,
  emailAuthInspectorManifest,
  encodingDetectorManifest,
  envDiffManifest,
  envEditorManifest,
  envJsonConverterManifest,
  envValidatorManifest,
  environmentVariablesManifest,
  epochTimelineVisualizerManifest,
  errorCodeReferenceManifest,
  escapeUnescapeToolkitManifest,
  eventLogViewerManifest,
  exifViewerManifest,
  expressionEvaluatorManifest,
  extractColumnsManifest,
  fileBase64Manifest,
  fileEntropyAnalyzerManifest,
  fileHashManifest,
  fileInspectorManifest,
  fileSplitJoinManifest,
  fileTypeDetectorManifest,
  findReplaceTextManifest,
  flexboxPlaygroundManifest,
  folderSizeAnalyzerManifest,
  gitCommandBuilderManifest,
  gitCommandExplainerManifest,
  gitDiffManifest,
  gitRemoteInspectorManifest,
  gitUrlParserManifest,
  gitignoreGeneratorManifest,
  gitignoreTesterManifest,
  globTesterManifest,
  gradientGeneratorManifest,
  hashManifestManifest,
  hashManifest,
  hexDiffManifest,
  hexDumpManifest,
  hexEditorManifest,
  hexTextConverterManifest,
  hmacGeneratorManifest,
  hostnameResolverManifest,
  htmlEntitiesManifest,
  htmlEntityExplorerManifest,
  htmlFormatterManifest,
  htmlJsxConverterManifest,
  htmlPreviewManifest,
  httpDigestAuthHelperManifest,
  httpHeaderInspectorManifest,
  httpRequestBuilderManifest,
  httpResponseViewerManifest,
  httpStatusManifest,
  httpsConfigAnalyzerManifest,
  imageCompressorManifest,
  imageCropperManifest,
  imageFormatConverterManifest,
  imageMetadataInspectorManifest,
  imageResizerManifest,
  iniFormatterManifest,
  installedSoftwareManifest,
  invisibleCharScannerManifest,
  ipAddressInspectorManifest,
  ipv4IntegerConverterManifest,
  ipv6ExplorerManifest,
  jsPlaygroundManifest,
  jsonFlattenManifest,
  jsonLdTesterManifest,
  jsonMergeManifest,
  jsonPatchGenerateManifest,
  jsonPatchTestManifest,
  jsonPointerManifest,
  jsonQueryManifest,
  jsonSchemaValidatorManifest,
  jsonSortKeysManifest,
  jsonManifest,
  jsonlViewerManifest,
  jwksToPemManifest,
  jwksViewerManifest,
  jwtClaimsAnalyzerManifest,
  jwtExpirationVisualizerManifest,
  jwtSignerManifest,
  jwtVerifyManifest,
  jwtManifest,
  k8sCronjobTesterManifest,
  k8sManifestDiffManifest,
  k8sManifestValidatorManifest,
  k8sQuantityConverterManifest,
  k8sResourceCalculatorManifest,
  k8sSecretBase64Manifest,
  keywordFrequencyAnalyzerManifest,
  ksuidToolsManifest,
  kubeconfigInspectorManifest,
  largeFileInspectorManifest,
  latencyMonitorManifest,
  lineOrderToolsManifest,
  linePrefixNumberingManifest,
  liveCertificateChainManifest,
  localNetworkManifest,
  lockfileInspectorManifest,
  loremIpsumGeneratorManifest,
  macAddressInspectorManifest,
  machoHeaderViewerManifest,
  markdownWorkspaceManifest,
  markdownManifest,
  matrixCalculatorManifest,
  metaTagGeneratorManifest,
  mimeTypesManifest,
  missingEnvVarDetectorManifest,
  mockDataStudioManifest,
  modelGeneratorManifest,
  msgpackDecoderManifest,
  mtuDiscoveryManifest,
  multipartFormBuilderManifest,
  nanoidGeneratorManifest,
  networkDiagnosticBundleManifest,
  numberBaseManifest,
  numberTheoryToolkitManifest,
  numericRepresentationInspectorManifest,
  oauthPlaygroundManifest,
  oauthScopeParserManifest,
  oauthTokenInspectorManifest,
  oidcDiscoveryInspectorManifest,
  opengraphPreviewManifest,
  packageMetadataInspectorManifest,
  packetLossManifest,
  paletteGeneratorManifest,
  parquetViewerManifest,
  passwordGeneratorManifest,
  passwordStrengthAnalyzerManifest,
  pathEditorManifest,
  peHeaderViewerManifest,
  pemDerInspectorManifest,
  percentageRatioCalculatorManifest,
  pingManifest,
  pixelColorPickerManifest,
  pkceGeneratorManifest,
  pkceVerifierManifest,
  pkcs12InspectorManifest,
  portProcessLookupManifest,
  portScannerManifest,
  processViewerManifest,
  programmerCalculatorManifest,
  propertiesParserManifest,
  protobufDecoderManifest,
  publicIpManifest,
  punycodeConverterManifest,
  pythonPlaygroundManifest,
  qrCodeGeneratorManifest,
  qrCodeScannerManifest,
  queryStringManifest,
  randomDataGeneratorManifest,
  rangeGeneratorManifest,
  rangeHeaderBuilderManifest,
  recurrenceRuleManifest,
  regexBenchmarkManifest,
  regexFlavorConverterManifest,
  regexGeneratorManifest,
  regexVisualizerManifest,
  regexManifest,
  registryEditorManifest,
  relativeTimeParserManifest,
  resolutionCalculatorManifest,
  resxToolManifest,
  reverseDnsManifest,
  revocationInspectorManifest,
  richTextEditorManifest,
  rotCipherManifest,
  routeComparisonManifest,
  runtimeDetectorManifest,
  scheduledTasksManifest,
  schemaDiffManifest,
  scientificNotationConverterManifest,
  secretDetectorManifest,
  semverComparatorManifest,
  servicesViewerManifest,
  slugGeneratorManifest,
  smartQuotesNormalizerManifest,
  snowflakeIdToolsManifest,
  soundexMetaphoneManifest,
  sqlDialectConverterManifest,
  sqlFormatterToolManifest,
  sqlParameterizerManifest,
  sqlQueryExplainerManifest,
  sqlSyntaxCheckerManifest,
  sqliteViewerManifest,
  sshKeyToolsManifest,
  stackTraceFormatterManifest,
  starttlsInspectorManifest,
  startupProgramsManifest,
  statisticsCalculatorManifest,
  stopwatchCountdownManifest,
  stringSimilarityCalculatorManifest,
  structuredDataConverterManifest,
  subnetCalculatorManifest,
  svgDataUriManifest,
  svgViewerManifest,
  systemChangesManifest,
  tailwindColorMatcherManifest,
  tcpPortTesterManifest,
  templateRendererManifest,
  textInspectorManifest,
  textTokenizerNgramManifest,
  timezoneConverterManifest,
  timezoneOffsetComparatorManifest,
  tlsInspectorManifest,
  tomlFormatterManifest,
  tracerouteManifest,
  treeSearchManifest,
  udpPortTesterManifest,
  ulidToolsManifest,
  unicodeCharacterInspectorManifest,
  unicodeCodePointConverterManifest,
  unicodeNormalizationManifest,
  unicodeTableManifest,
  unixTimestampManifest,
  urlEncodeManifest,
  urlInspectorManifest,
  urlNormalizerManifest,
  urlPercentInspectorManifest,
  urlSafetyInspectorManifest,
  userAgentManifest,
  uuidManifest,
  watchedFoldersManifest,
  weekNumberCalculatorManifest,
  whitespaceCleanerManifest,
  whoisLookupManifest,
  windowsFeaturesManifest,
  x509CertificateInspectorManifest,
  xmlCsvManifest,
  xmlFormatterManifest,
  xmlXpathManifest,
  xmlXsdValidatorManifest,
  yamlAnchorsManifest,
  yamlJsonManifest,
  yamlLinterManifest,
  yamlMergeManifest,
  yamlPathManifest,
];
