/**
 * A curated selection of IANA-registered media types
 * (https://www.iana.org/assignments/media-types/media-types.xhtml), spanning
 * all 9 top-level types. The full registry runs to 1000+ entries, most of
 * which are narrow vendor-specific formats; this file favors the types a
 * developer actually looks up (standard web formats, common document/archive
 * formats, and well-known audio/video/image/font codecs) over exhaustively
 * transcribing the entire registry, which would risk introducing transcription
 * errors into a reference tool. Last reviewed 2026-09-20.
 */

export type MimeTopLevelType =
  | 'application'
  | 'audio'
  | 'font'
  | 'image'
  | 'message'
  | 'model'
  | 'multipart'
  | 'text'
  | 'video';

export interface MimeTypeEntry {
  readonly type: string;
  readonly topLevelType: MimeTopLevelType;
}

function entries(topLevelType: MimeTopLevelType, subtypes: readonly string[]): readonly MimeTypeEntry[] {
  return subtypes.map((subtype) => ({ type: `${topLevelType}/${subtype}`, topLevelType }));
}

export const MIME_TYPES: readonly MimeTypeEntry[] = [
  ...entries('application', [
    'json',
    'ld+json',
    'xml',
    'xhtml+xml',
    'pdf',
    'zip',
    'gzip',
    'x-www-form-urlencoded',
    'octet-stream',
    'rtf',
    'atom+xml',
    'rss+xml',
    'soap+xml',
    'manifest+json',
    'wasm',
    'javascript',
    'ecmascript',
    'graphql',
    'sql',
    'sparql-query',
    'sparql-results+json',
    'sparql-results+xml',
    'epub+zip',
    'java-archive',
    'ogg',
    'postscript',
    'font-sfnt',
    'font-woff',
    'font-woff2',
    'vnd.ms-excel',
    'vnd.ms-powerpoint',
    'vnd.ms-fontobject',
    'vnd.openxmlformats-officedocument.wordprocessingml.document',
    'vnd.openxmlformats-officedocument.wordprocessingml.template',
    'vnd.openxmlformats-officedocument.spreadsheetml.sheet',
    'vnd.openxmlformats-officedocument.spreadsheetml.template',
    'vnd.openxmlformats-officedocument.presentationml.presentation',
    'vnd.openxmlformats-officedocument.presentationml.template',
    'vnd.oasis.opendocument.text',
    'vnd.oasis.opendocument.spreadsheet',
    'vnd.oasis.opendocument.presentation',
    'vnd.oasis.opendocument.graphics',
    'vnd.api+json',
    'vnd.geo+json',
    'vnd.google-earth.kml+xml',
    'vnd.google-earth.kmz',
    'vnd.mozilla.xul+xml',
    'vnd.visio',
    'vnd.rar',
    'vnd.debian.binary-package',
    'cbor',
    'jose',
    'jose+json',
    'jwt',
    'jwk+json',
    'jwk-set+json',
    'pkcs7-mime',
    'pkcs7-signature',
    'pkcs8',
    'pkcs10',
    'pkix-cert',
    'pkix-crl',
    'x-pki-message',
    'grpc',
    'toml',
    'yang',
    'xml-dtd',
    'xml-patch+xml',
    'xop+xml',
    'dns',
    'dicom',
    'zlib',
    'zstd',
    'x-bzip2',
    'x-tar',
    'node',
  ]),
  ...entries('audio', [
    'basic',
    'mpeg',
    'mp4',
    'ogg',
    'opus',
    'aac',
    'flac',
    'webm',
    'midi',
    'x-midi',
    'vnd.wave',
    'vnd.dlna.adts',
    '3gpp',
    '3gpp2',
    'g722',
    'ac3',
    'eac3',
  ]),
  ...entries('font', ['ttf', 'otf', 'woff', 'woff2', 'collection', 'sfnt']),
  ...entries('image', [
    'png',
    'jpeg',
    'gif',
    'webp',
    'svg+xml',
    'bmp',
    'tiff',
    'avif',
    'heic',
    'heic-sequence',
    'heif',
    'heif-sequence',
    'jp2',
    'jxl',
    'apng',
    'vnd.microsoft.icon',
    'vnd.adobe.photoshop',
    'vnd.djvu',
    'vnd.dwg',
    'dicom-rle',
    'x-xbitmap',
  ]),
  ...entries('message', [
    'rfc822',
    'http',
    'partial',
    'external-body',
    'global',
    'delivery-status',
    'disposition-notification',
    'feedback-report',
    'sip',
    's-http',
  ]),
  ...entries('model', [
    'gltf+json',
    'gltf-binary',
    'obj',
    'stl',
    'mtl',
    'vrml',
    'x3d+xml',
    'x3d+fastinfoset',
    '3mf',
    'step',
    'iges',
    'e57',
  ]),
  ...entries('multipart', [
    'form-data',
    'mixed',
    'alternative',
    'related',
    'byteranges',
    'signed',
    'encrypted',
    'digest',
    'report',
    'x-mixed-replace',
  ]),
  ...entries('text', [
    'plain',
    'html',
    'css',
    'csv',
    'javascript',
    'markdown',
    'xml',
    'calendar',
    'vcard',
    'vtt',
    'richtext',
    'tab-separated-values',
    'uri-list',
    'event-stream',
    'n3',
    'turtle',
    'dns',
    'troff',
    'csv-schema',
    'x-suse-ymp',
  ]),
  ...entries('video', [
    'mp4',
    'mpeg',
    'ogg',
    'webm',
    'quicktime',
    'vnd.avi',
    'x-msvideo',
    '3gpp',
    '3gpp2',
    'h264',
    'h265',
    'mp2t',
    'jpeg',
    'raw',
  ]),
];
